package barcoding_test

import (
	_ "embed"
	"fmt"
	"strings"
	"testing"

	"github.com/koeng101/dnadesign/lib/bio"
	"github.com/koeng101/dnadesign/lib/sequencing/barcoding"
)

func ExampleDualBarcodeSequence() {
	// Add in our barcode set. This is an abrdiged version of a full
	// dual barcode plate.
	primerSetCsv := `O1,GAAGCTCAAGCGTAAGCGGA,GAACCACAACCTTAACCTGA
B15,GCGGAAGCGCAAGCCTAAGC,GACCTAGACCGAGACCCAGT
J22,TAACGTGAACGTCAACGGTA,GTGGTAGTGGGAGTGGCAGT
E20,GGTGAAGGTCAAGGGTAAGG,GTTCCAGTGACAGTGTTAGT
C22,GAAGGACAAGGTTAAGGTGA,GTGGTAGTGGGAGTGGCAGT
A15,GGAAAAGCAAAACTAAAACG,GACCTAGACCGAGACCCAGT`
	// Add in reads. The following are real reads from a Nanopore sequencing
	// run, barcoded with the above barcodes.
	reads := `@ed433f97-a7e9-4b95-be59-2e18bda14fc2 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=18 ch=90 start_time=2024-02-06T15:59:33.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=ed433f97-a7e9-4b95-be59-2e18bda14fc2 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
TGTCCCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTGCGGAAGCGCAAGCCTAAGCGTAAAACGACGGCCAGTGAATCCGTAATCATGGTCATAGCTGTTTCCTGACTGGGTCTCGGTCTAGGTCAGGTGCTGAAGTTGTCGGTGTTGCTTGTGTTAACCTTTACGATGGT
+
'(*()(''*--.6+***+6---+,-./=CBDFIKSSGHFCHB@886797777ABCKICGDCAEFCBFDFSIHLSSGSSJSJISFMKSISJSOGSBA@??...--4?IFMRGSPGSRHLJGLEB(((18::=KMSGSJNSSGRGKSHGCCCECLSJRKIKHKJNHMJGH6.,)))((((())//---//0=8756:8892+&%%'((+
@8c5cf4e3-2595-4e1e-b014-9a6f9998b3d3 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=31 ch=12 start_time=2024-02-06T15:59:35.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=8c5cf4e3-2595-4e1e-b014-9a6f9998b3d3 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
TTGTCCTCTGCTTGGTTTCATTACGTATTGCTAACCAGCACAGAAGACACCGACAACTTTCTTCAGCACCTAGGCGAAGGCCAGCGTAAACGACGGCCAGTGGCTAAGGCGAAGGCCAGCGTAAAACAACACCCATGATCATCATCATCGTCATCACTCTTCCTCCGAGTCTGGC
+
%%%%$###$%&&'%''))))*-,,....0446-,*(('(()()()'((''(//123441,'',--/21112/..-.14457=>;;220-*()),-.234=?>>?=64443//001<34**+3/-,,*())'&(''))))*)*,++,,,*&&&&(((**%%%%(,)'&%%%%&%'&
@07c30f6c-5d40-4422-8caf-acca91369ae2 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=8 ch=68 start_time=2024-02-06T15:59:30.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=07c30f6c-5d40-4422-8caf-acca91369ae2 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
ATGTCCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTCCCAGGAAACAGCTATGACCATGAACCACAACCTTAACCTGACAGGAAACAGCTATGACCATGATTACGGATTCACTGGCCGTCGTTTGCTCACCTTTTGCCGCTTCCCCTCGTATGCGGATGCGCATGCCCAGGAAACAGCTATGACCATGATTACGGATTCACTGGCCGTCGTTTTACTCCGCTTACGCTTGAGCTTCACTGGCAGCGTTTTACTCCGCTTACGCTTGAGCTTCACTGGCCGTCGTTTATCCGCTCATG
+
$%&&$$$$&'))10235****+55677?@@ABKNEKFHEFDEDEEEFGKMGKECCCDHFFEAA500188:???BBBEHGELLDDDBBC@ABBCDBAABAHEEHDDAAA?BFJFEFEEDDCGEFEGGFGEEDDFJMFD><=<<>>>@<<;88:77765577,++++++++31(12/...../:2<>?@BHGKGKJGEDCEEBCC?0FFCDGKFEDCCFDDFFKSHHMHFEEEDGFFFDEFE>79877857>B==<<<ABBBKHEIA==<<=;9:;A/--+(&&&*-0*8=?CEIFGDEGCMOEGEHEGG?????DDDH<;:;;AEFB==<%$$$
@d990f6ac-ba6b-4f91-810d-0982b3d300bd runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=30 ch=3 start_time=2024-02-06T15:59:37.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=d990f6ac-ba6b-4f91-810d-0982b3d300bd basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
ATGTCCTTGTTCTTCGACATTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTAAGCTCAAGCGTAAGCGGAGTAAAACGACGGCCAGTGTTATTGAATAAATCAGATTTGCCATGGTCTAGCTGTTTCCTGCGATATAGATATGCATATCCATGGTCATAGCTGTTTCCTGTCAGGTTAAGGTTGTGGTTCAGGTGCTGAAGAAAGTTGTCGTTTCTCTCTAATG
+
%%%&&)((''(&&&'34544444454489:CFFGHFNFFE;:442.)&&&+()12=>>??665,+,(((////00566<<<@BBCCLESGMPILIMG=====HECGFEJF))2000;34444)))))*(:BCDDDFFCAA?@CA>>9:CDDCAA>8.,,,,2)))))43844444@ADDGLJ=@DG5H@@B10000EEDFEFSKPGSLNFESHHKJSKHGCABB@BD=;))&&$$$$%%'%&'*
@66889973-c411-4d86-8d80-5040be1f91d1 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=20 ch=70 start_time=2024-02-06T15:59:36.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=66889973-c411-4d86-8d80-5040be1f91d1 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
TATATGTCCTCTACTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTTAACGTGAACGTCAACGGTAGTAAAACGACGGCCAGTCCCACTACCGGCGTATGGTCATAGCTGTTTCCTCGACTGCCACTCCCACTACCACAGCTGCTGAAGAAAGTTGTAATTTGTCTTTGTGTTAACCTTCACGATAAAC
+
&'(),,)%$###$%*,,,EFDEDFFJELHSHSJSIISSSOSSKLJKIKKKHNOIIJILKOKSMLSIEELGDMGJ=::<>=3334-----44CHDIHHJHSHHHIGSSGHHS@?;89A543**))(()'))*@BCDHJJSFF<D4,((()DSKKLIFBDCFL?>>22('&((())))))-,(*0,,(((('''',+.-/@@>557992&&&&((''&&
@6e9f5fbd-cd9c-4aaf-9831-3fc6c957429a runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=24 ch=70 start_time=2024-02-06T15:59:38.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=6e9f5fbd-cd9c-4aaf-9831-3fc6c957429a basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
TTTGCCTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTGTGGTAGTGGGAGTGGCAGTCAGGAAACAGCTATGACCATGGTGGTAGTGGGACTGGCCGTGGTTTACGCTTAGCTTAAGCTTGTGCTTATGATTCACTGGCCGTCGTTTTACTCACCTTAACCTTGTCCTTAGGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCTTAGCAATACGT
+
$&&&&'%%,+++.**++'****+./00;<?76666GSIGLGIGGFHGGJGSQMNHIGHFI611=/./00HJGJOJJMIJSMMQSIMGEJECJ<:::<EJGLHLSSNNSSJOSGSQPSSJISFSIMJJLSGJIR++++4+1001-%%%&,,;?@@F;;<MFKKNKIKGNSRSHIJGGS??@@@D=FGEEDHFISSLGKSSOJPJIEGHFHIKSJSNSGSLSKNSIJFIIGFJDC<BBKC;77333++/,,,+*)(
@4f88db81-18a2-4353-bde1-2b539425b79a runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=125 ch=46 start_time=2024-02-06T16:00:54.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=4f88db81-18a2-4353-bde1-2b539425b79a basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
TATCTGTGTACTTGGTTCAGTTAGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTGTACCAGTTACAGTTTTAGTCAGGAAACAGCTATGACCATGATTACGGATTCACTGGCCGTCGTTTTACTAGCCTTGCCCTTTCCCTTAACTGGCCGTGGTTTTG
+
'&'&&$$$%&))2/00::;5552((((358;?<<<<<?>?>>>>==998877777:<;<?>==;::<<=??@98888;776668777889932222567889:9:98676765566=:;::;>=><<<<<=>==>??:8;87779;>>=>?>CA;CA/>87889;?@>>8665-*'
@30119e9e-19a0-4174-be00-bc61117ce8d6 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=57 ch=65 start_time=2024-02-06T16:00:40.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=30119e9e-19a0-4174-be00-bc61117ce8d6 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
GTGTAACCTACTGGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTGTGAAGGTCAAGGGTAAGGGTAAAACGACGGCCAGTCACCAACCATAACCAGAACCATTAAAACGACGGCCAGTGAATCCGTAATCATGGTCATAGCTTTCCTGACTAACACTGTCACTGGAACATGGTCTAGCTGTTTCCTGGTGATAGGTG
+
$$$((45;=@GG7778454446889:AABCFSSOKPIDESGISSGJJSFSHBBB@>??EFBEJKGHGSSQNJJSKMSSOFFDFELFMSSNMHSOMNSIOHSNSSQSLLJSEHHGSISISKSHSHKDC/---,-47?@@ABSGFJICESNFKHSJIJSJSGHJKSKKRF?:7(<70111PKLSKSJSLHPNMFSOSJSLSLHIOGQSHFHA<@F<<<;:=)('''
@a931cb47-d99e-43e0-b6e1-7a52777ab1a2 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=39 ch=70 start_time=2024-02-06T16:00:43.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=a931cb47-d99e-43e0-b6e1-7a52777ab1a2 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
ATGTTGCCTACCTACTTGGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCCGACAACTTTCTTCAGCACCTGCCAAGCGTAAAACGACGGCCAGTGGAAAAGCAAAACTAAAACGGTAAAACGACGGCCAGTGGAAAAGCAAAACTAAAACGGTAAACGACGGCCAGTTACGTTATTTGCTTTTCATGGTCATAGCTGTTTCCTGACTGGGTCTCGGTCTAGGTCAGGTGCTGAAGAAAGTTGTCGGTGTCTTTGTGTTAACCACGATGCGTTGT
+
%%%%%%####$%(*+,)&''));::80-''')0000BCFJOSNLQJKJKRSMSFKLSDHIMGJEHDABFCCHIJKSSISHGJMSKSSKSOLSJSJIOJMSMNRKJKSJQLISGHGIHSJHSLJKSMISJEEBBCBH>=:/---849000>@GEEEJOKJIJHGSISIOMHKKGFGFJMGHHROIPSIJSSJKSLSMMSKJSJIIIKNMMEISKMLSKSHJPHLMJNQLHGRJKKKSHKKOMISOSGFJIOSSLSOSSSSNMSIFH876'&'(....+++(%
@d8b0c139-fdc3-4c31-9cdc-0c6d1b5e14a2 runid=599e6407c739adc4ecb3169cea4c881b04635ea8 read=48 ch=26 start_time=2024-02-06T16:00:46.914899-08:00 flow_cell_id=ARF133 protocol_group_id=nseq30 sample_id=u12-u13-u14-u15-u16-u17-u18-u19-B4-B5 barcode=barcode01 barcode_alias=barcode01 parent_read_id=d8b0c139-fdc3-4c31-9cdc-0c6d1b5e14a2 basecall_model_version_id=dna_r10.4.1_e8.2_400bps_sup@v4.2.0
GTGTGTACTTCGTTCAGTTACGTATGCTTAGTTGTGAACACAAAGACACCGACAACTTCTTCAGCACCTTCTTGATCTTCATCTGTATCCAGGAAACAGCTATGACCATGCCTGAACCTCAACCGTAACCCAGGAAACAGCTATGACCATGCCTGAACCTCAACCGTAACCCAGGAAACAGCTATGACCATGATTCATCACTGGCCGTGGTTTCGGTTCTGGT
+
$$$%%%%&',*+,//;=:9771111,-+*&&%%%%%'.1389:987777844443553((50+,,88:;2///;6555597677764334578879999:977778888888;=;99888766534424551666688767644445776777:<;:998986652222378*9:::<;:99876322211//..,,,,-0667873333488('''122../
`
	primerSet, _ := barcoding.ParseDualPrimerSet(strings.NewReader(primerSetCsv))
	parser := bio.NewFastqParser(strings.NewReader(reads))
	records, _ := parser.Parse()

	var wells []string
	for _, record := range records {
		well, _ := barcoding.DualBarcodeSequence(record.Sequence, "gtaaaacgacggccagt", "caggaaacagctatgaccatg", primerSet)
		if well != "" {
			wells = append(wells, well)
		}
	}

	fmt.Println(wells)
	// Output: [B15 O1 O1 J22 C22 E20]
}

func TestDualBarcodesToPrimerSet(t *testing.T) {
	dualBarcodes := []barcoding.DualBarcode{{Name: "test", Forward: "ATG", Reverse: "TAA"}}
	primerSet := barcoding.DualBarcodesToPrimerSet(dualBarcodes)
	if len(primerSet.ForwardBarcodes) != 1 || len(primerSet.ReverseBarcodes) != 1 {
		t.Errorf("Should have gotten barcode length of 1.")
	}
}

var Barcodes = barcoding.DualBarcodesToPrimerSet([]barcoding.DualBarcode{
	barcoding.DualBarcode{"A1", "GGAAAAGCAAAACTAAAACG", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"C1", "GAAGGACAAGGTTAAGGTGA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"E1", "GGTGAAGGTCAAGGGTAAGG", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"G1", "TAAGGGGAAGGGCAAGGCTA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"I1", "GGCTAAGGCGAAGGCCAAGC", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"K1", "CAAGCATAAGCAGAAGCACA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"M1", "GCACAAGCTTAAGCTGAAGC", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"O1", "GAAGCTCAAGCGTAAGCGGA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"A2", "GGAAAAGCAAAACTAAAACG", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"C2", "GAAGGACAAGGTTAAGGTGA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"E2", "GGTGAAGGTCAAGGGTAAGG", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"G2", "TAAGGGGAAGGGCAAGGCTA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"I2", "GGCTAAGGCGAAGGCCAAGC", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"K2", "CAAGCATAAGCAGAAGCACA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"M2", "GCACAAGCTTAAGCTGAAGC", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"O2", "GAAGCTCAAGCGTAAGCGGA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"A3", "GGAAAAGCAAAACTAAAACG", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"C3", "GAAGGACAAGGTTAAGGTGA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"E3", "GGTGAAGGTCAAGGGTAAGG", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"G3", "TAAGGGGAAGGGCAAGGCTA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"I3", "GGCTAAGGCGAAGGCCAAGC", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"K3", "CAAGCATAAGCAGAAGCACA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"M3", "GCACAAGCTTAAGCTGAAGC", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"O3", "GAAGCTCAAGCGTAAGCGGA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"A4", "GGAAAAGCAAAACTAAAACG", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"C4", "GAAGGACAAGGTTAAGGTGA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"E4", "GGTGAAGGTCAAGGGTAAGG", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"G4", "TAAGGGGAAGGGCAAGGCTA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"I4", "GGCTAAGGCGAAGGCCAAGC", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"K4", "CAAGCATAAGCAGAAGCACA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"M4", "GCACAAGCTTAAGCTGAAGC", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"O4", "GAAGCTCAAGCGTAAGCGGA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"A5", "GGAAAAGCAAAACTAAAACG", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"C5", "GAAGGACAAGGTTAAGGTGA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"E5", "GGTGAAGGTCAAGGGTAAGG", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"G5", "TAAGGGGAAGGGCAAGGCTA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"I5", "GGCTAAGGCGAAGGCCAAGC", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"K5", "CAAGCATAAGCAGAAGCACA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"M5", "GCACAAGCTTAAGCTGAAGC", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"O5", "GAAGCTCAAGCGTAAGCGGA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"A6", "GGAAAAGCAAAACTAAAACG", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"C6", "GAAGGACAAGGTTAAGGTGA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"E6", "GGTGAAGGTCAAGGGTAAGG", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"G6", "TAAGGGGAAGGGCAAGGCTA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"I6", "GGCTAAGGCGAAGGCCAAGC", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"K6", "CAAGCATAAGCAGAAGCACA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"M6", "GCACAAGCTTAAGCTGAAGC", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"O6", "GAAGCTCAAGCGTAAGCGGA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"A7", "GGAAAAGCAAAACTAAAACG", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"C7", "GAAGGACAAGGTTAAGGTGA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"E7", "GGTGAAGGTCAAGGGTAAGG", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"G7", "TAAGGGGAAGGGCAAGGCTA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"I7", "GGCTAAGGCGAAGGCCAAGC", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"K7", "CAAGCATAAGCAGAAGCACA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"M7", "GCACAAGCTTAAGCTGAAGC", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"O7", "GAAGCTCAAGCGTAAGCGGA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"A8", "GGAAAAGCAAAACTAAAACG", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"C8", "GAAGGACAAGGTTAAGGTGA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"E8", "GGTGAAGGTCAAGGGTAAGG", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"G8", "TAAGGGGAAGGGCAAGGCTA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"I8", "GGCTAAGGCGAAGGCCAAGC", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"K8", "CAAGCATAAGCAGAAGCACA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"M8", "GCACAAGCTTAAGCTGAAGC", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"O8", "GAAGCTCAAGCGTAAGCGGA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"A9", "GGAAAAGCAAAACTAAAACG", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"C9", "GAAGGACAAGGTTAAGGTGA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"E9", "GGTGAAGGTCAAGGGTAAGG", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"G9", "TAAGGGGAAGGGCAAGGCTA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"I9", "GGCTAAGGCGAAGGCCAAGC", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"K9", "CAAGCATAAGCAGAAGCACA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"M9", "GCACAAGCTTAAGCTGAAGC", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"O9", "GAAGCTCAAGCGTAAGCGGA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"A10", "GGAAAAGCAAAACTAAAACG", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"C10", "GAAGGACAAGGTTAAGGTGA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"E10", "GGTGAAGGTCAAGGGTAAGG", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"G10", "TAAGGGGAAGGGCAAGGCTA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"I10", "GGCTAAGGCGAAGGCCAAGC", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"K10", "CAAGCATAAGCAGAAGCACA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"M10", "GCACAAGCTTAAGCTGAAGC", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"O10", "GAAGCTCAAGCGTAAGCGGA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"A11", "GGAAAAGCAAAACTAAAACG", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"C11", "GAAGGACAAGGTTAAGGTGA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"E11", "GGTGAAGGTCAAGGGTAAGG", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"G11", "TAAGGGGAAGGGCAAGGCTA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"I11", "GGCTAAGGCGAAGGCCAAGC", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"K11", "CAAGCATAAGCAGAAGCACA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"M11", "GCACAAGCTTAAGCTGAAGC", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"O11", "GAAGCTCAAGCGTAAGCGGA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"A12", "GGAAAAGCAAAACTAAAACG", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"C12", "GAAGGACAAGGTTAAGGTGA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"E12", "GGTGAAGGTCAAGGGTAAGG", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"G12", "TAAGGGGAAGGGCAAGGCTA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"I12", "GGCTAAGGCGAAGGCCAAGC", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"K12", "CAAGCATAAGCAGAAGCACA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"M12", "GCACAAGCTTAAGCTGAAGC", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"O12", "GAAGCTCAAGCGTAAGCGGA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"A13", "GGAAAAGCAAAACTAAAACG", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"C13", "GAAGGACAAGGTTAAGGTGA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"E13", "GGTGAAGGTCAAGGGTAAGG", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"G13", "TAAGGGGAAGGGCAAGGCTA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"I13", "GGCTAAGGCGAAGGCCAAGC", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"K13", "CAAGCATAAGCAGAAGCACA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"M13", "GCACAAGCTTAAGCTGAAGC", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"O13", "GAAGCTCAAGCGTAAGCGGA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"A14", "GGAAAAGCAAAACTAAAACG", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"C14", "GAAGGACAAGGTTAAGGTGA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"E14", "GGTGAAGGTCAAGGGTAAGG", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"G14", "TAAGGGGAAGGGCAAGGCTA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"I14", "GGCTAAGGCGAAGGCCAAGC", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"K14", "CAAGCATAAGCAGAAGCACA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"M14", "GCACAAGCTTAAGCTGAAGC", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"O14", "GAAGCTCAAGCGTAAGCGGA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"A15", "GGAAAAGCAAAACTAAAACG", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"C15", "GAAGGACAAGGTTAAGGTGA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"E15", "GGTGAAGGTCAAGGGTAAGG", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"G15", "TAAGGGGAAGGGCAAGGCTA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"I15", "GGCTAAGGCGAAGGCCAAGC", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"K15", "CAAGCATAAGCAGAAGCACA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"M15", "GCACAAGCTTAAGCTGAAGC", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"O15", "GAAGCTCAAGCGTAAGCGGA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"A16", "GGAAAAGCAAAACTAAAACG", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"C16", "GAAGGACAAGGTTAAGGTGA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"E16", "GGTGAAGGTCAAGGGTAAGG", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"G16", "TAAGGGGAAGGGCAAGGCTA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"I16", "GGCTAAGGCGAAGGCCAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"K16", "CAAGCATAAGCAGAAGCACA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"M16", "GCACAAGCTTAAGCTGAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"O16", "GAAGCTCAAGCGTAAGCGGA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"A17", "GGAAAAGCAAAACTAAAACG", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"C17", "GAAGGACAAGGTTAAGGTGA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"E17", "GGTGAAGGTCAAGGGTAAGG", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"G17", "TAAGGGGAAGGGCAAGGCTA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"I17", "GGCTAAGGCGAAGGCCAAGC", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"K17", "CAAGCATAAGCAGAAGCACA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"M17", "GCACAAGCTTAAGCTGAAGC", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"O17", "GAAGCTCAAGCGTAAGCGGA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"A18", "GGAAAAGCAAAACTAAAACG", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"C18", "GAAGGACAAGGTTAAGGTGA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"E18", "GGTGAAGGTCAAGGGTAAGG", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"G18", "TAAGGGGAAGGGCAAGGCTA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"I18", "GGCTAAGGCGAAGGCCAAGC", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"K18", "CAAGCATAAGCAGAAGCACA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"M18", "GCACAAGCTTAAGCTGAAGC", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"O18", "GAAGCTCAAGCGTAAGCGGA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"A19", "GGAAAAGCAAAACTAAAACG", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"C19", "GAAGGACAAGGTTAAGGTGA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"E19", "GGTGAAGGTCAAGGGTAAGG", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"G19", "TAAGGGGAAGGGCAAGGCTA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"I19", "GGCTAAGGCGAAGGCCAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"K19", "CAAGCATAAGCAGAAGCACA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"M19", "GCACAAGCTTAAGCTGAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"O19", "GAAGCTCAAGCGTAAGCGGA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"A20", "GGAAAAGCAAAACTAAAACG", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"C20", "GAAGGACAAGGTTAAGGTGA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"E20", "GGTGAAGGTCAAGGGTAAGG", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"G20", "TAAGGGGAAGGGCAAGGCTA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"I20", "GGCTAAGGCGAAGGCCAAGC", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"K20", "CAAGCATAAGCAGAAGCACA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"M20", "GCACAAGCTTAAGCTGAAGC", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"O20", "GAAGCTCAAGCGTAAGCGGA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"A21", "GGAAAAGCAAAACTAAAACG", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"C21", "GAAGGACAAGGTTAAGGTGA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"E21", "GGTGAAGGTCAAGGGTAAGG", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"G21", "TAAGGGGAAGGGCAAGGCTA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"I21", "GGCTAAGGCGAAGGCCAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"K21", "CAAGCATAAGCAGAAGCACA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"M21", "GCACAAGCTTAAGCTGAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"O21", "GAAGCTCAAGCGTAAGCGGA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"A22", "GGAAAAGCAAAACTAAAACG", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"C22", "GAAGGACAAGGTTAAGGTGA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"E22", "GGTGAAGGTCAAGGGTAAGG", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"G22", "TAAGGGGAAGGGCAAGGCTA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"I22", "GGCTAAGGCGAAGGCCAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"K22", "CAAGCATAAGCAGAAGCACA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"M22", "GCACAAGCTTAAGCTGAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"O22", "GAAGCTCAAGCGTAAGCGGA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"A23", "GGAAAAGCAAAACTAAAACG", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"C23", "GAAGGACAAGGTTAAGGTGA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"E23", "GGTGAAGGTCAAGGGTAAGG", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"G23", "TAAGGGGAAGGGCAAGGCTA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"I23", "GGCTAAGGCGAAGGCCAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"K23", "CAAGCATAAGCAGAAGCACA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"M23", "GCACAAGCTTAAGCTGAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"O23", "GAAGCTCAAGCGTAAGCGGA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"A24", "GGAAAAGCAAAACTAAAACG", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"C24", "GAAGGACAAGGTTAAGGTGA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"E24", "GGTGAAGGTCAAGGGTAAGG", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"G24", "TAAGGGGAAGGGCAAGGCTA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"I24", "GGCTAAGGCGAAGGCCAAGC", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"K24", "CAAGCATAAGCAGAAGCACA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"M24", "GCACAAGCTTAAGCTGAAGC", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"O24", "GAAGCTCAAGCGTAAGCGGA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"B1", "GCGGAAGCGCAAGCCTAAGC", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"D1", "TAAGCCGAAGCCCAACAACA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"F1", "ACATGAACATCAACAGTAAC", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"H1", "CGAGAACGACAACGTTAACG", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"J1", "TAACGTGAACGTCAACGGTA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"L1", "CGGTAACGGGAACGGCAACG", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"N1", "CAACGCTAACGCGAACGCCA", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"P1", "CGCCAACCATAACCAGAACC", "GAACCACAACCTTAACCTGA"},
	barcoding.DualBarcode{"B2", "GCGGAAGCGCAAGCCTAAGC", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"D2", "TAAGCCGAAGCCCAACAACA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"F2", "ACATGAACATCAACAGTAAC", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"H2", "CGAGAACGACAACGTTAACG", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"J2", "TAACGTGAACGTCAACGGTA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"L2", "CGGTAACGGGAACGGCAACG", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"N2", "CAACGCTAACGCGAACGCCA", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"P2", "CGCCAACCATAACCAGAACC", "CCTGAACCTCAACCGTAACC"},
	barcoding.DualBarcode{"B3", "GCGGAAGCGCAAGCCTAAGC", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"D3", "TAAGCCGAAGCCCAACAACA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"F3", "ACATGAACATCAACAGTAAC", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"H3", "CGAGAACGACAACGTTAACG", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"J3", "TAACGTGAACGTCAACGGTA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"L3", "CGGTAACGGGAACGGCAACG", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"N3", "CAACGCTAACGCGAACGCCA", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"P3", "CGCCAACCATAACCAGAACC", "TAACCGGAACCGCAACCCTA"},
	barcoding.DualBarcode{"B4", "GCGGAAGCGCAAGCCTAAGC", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"D4", "TAAGCCGAAGCCCAACAACA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"F4", "ACATGAACATCAACAGTAAC", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"H4", "CGAGAACGACAACGTTAACG", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"J4", "TAACGTGAACGTCAACGGTA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"L4", "CGGTAACGGGAACGGCAACG", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"N4", "CAACGCTAACGCGAACGCCA", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"P4", "CGCCAACCATAACCAGAACC", "CCCTAACCCGAACCCCATAT"},
	barcoding.DualBarcode{"B5", "GCGGAAGCGCAAGCCTAAGC", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"D5", "TAAGCCGAAGCCCAACAACA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"F5", "ACATGAACATCAACAGTAAC", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"H5", "CGAGAACGACAACGTTAACG", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"J5", "TAACGTGAACGTCAACGGTA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"L5", "CGGTAACGGGAACGGCAACG", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"N5", "CAACGCTAACGCGAACGCCA", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"P5", "CGCCAACCATAACCAGAACC", "GGATATGCATATCTATATCG"},
	barcoding.DualBarcode{"B6", "GCGGAAGCGCAAGCCTAAGC", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"D6", "TAAGCCGAAGCCCAACAACA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"F6", "ACATGAACATCAACAGTAAC", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"H6", "CGAGAACGACAACGTTAACG", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"J6", "TAACGTGAACGTCAACGGTA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"L6", "CGGTAACGGGAACGGCAACG", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"N6", "CAACGCTAACGCGAACGCCA", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"P6", "CGCCAACCATAACCAGAACC", "CGTATGCGGATGCGCATGCC"},
	barcoding.DualBarcode{"B7", "GCGGAAGCGCAAGCCTAAGC", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"D7", "TAAGCCGAAGCCCAACAACA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"F7", "ACATGAACATCAACAGTAAC", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"H7", "CGAGAACGACAACGTTAACG", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"J7", "TAACGTGAACGTCAACGGTA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"L7", "CGGTAACGGGAACGGCAACG", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"N7", "CAACGCTAACGCGAACGCCA", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"P7", "CGCCAACCATAACCAGAACC", "ATGCCTATGCCGATGCCCAT"},
	barcoding.DualBarcode{"B8", "GCGGAAGCGCAAGCCTAAGC", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"D8", "TAAGCCGAAGCCCAACAACA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"F8", "ACATGAACATCAACAGTAAC", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"H8", "CGAGAACGACAACGTTAACG", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"J8", "TAACGTGAACGTCAACGGTA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"L8", "CGGTAACGGGAACGGCAACG", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"N8", "CAACGCTAACGCGAACGCCA", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"P8", "CGCCAACCATAACCAGAACC", "CCCATCATCAGTATCAGGAT"},
	barcoding.DualBarcode{"B9", "GCGGAAGCGCAAGCCTAAGC", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"D9", "TAAGCCGAAGCCCAACAACA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"F9", "ACATGAACATCAACAGTAAC", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"H9", "CGAGAACGACAACGTTAACG", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"J9", "TAACGTGAACGTCAACGGTA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"L9", "CGGTAACGGGAACGGCAACG", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"N9", "CAACGCTAACGCGAACGCCA", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"P9", "CGCCAACCATAACCAGAACC", "AGGATCAGCATCACTATCAC"},
	barcoding.DualBarcode{"B10", "GCGGAAGCGCAAGCCTAAGC", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"D10", "TAAGCCGAAGCCCAACAACA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"F10", "ACATGAACATCAACAGTAAC", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"H10", "CGAGAACGACAACGTTAACG", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"J10", "TAACGTGAACGTCAACGGTA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"L10", "CGGTAACGGGAACGGCAACG", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"N10", "CAACGCTAACGCGAACGCCA", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"P10", "CGCCAACCATAACCAGAACC", "ATCACGATCACCATCTAGAT"},
	barcoding.DualBarcode{"B11", "GCGGAAGCGCAAGCCTAAGC", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"D11", "TAAGCCGAAGCCCAACAACA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"F11", "ACATGAACATCAACAGTAAC", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"H11", "CGAGAACGACAACGTTAACG", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"J11", "TAACGTGAACGTCAACGGTA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"L11", "CGGTAACGGGAACGGCAACG", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"N11", "CAACGCTAACGCGAACGCCA", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"P11", "CGCCAACCATAACCAGAACC", "TCTTGATCTTCATCTGTATC"},
	barcoding.DualBarcode{"B12", "GCGGAAGCGCAAGCCTAAGC", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"D12", "TAAGCCGAAGCCCAACAACA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"F12", "ACATGAACATCAACAGTAAC", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"H12", "CGAGAACGACAACGTTAACG", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"J12", "TAACGTGAACGTCAACGGTA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"L12", "CGGTAACGGGAACGGCAACG", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"N12", "CAACGCTAACGCGAACGCCA", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"P12", "CGCCAACCATAACCAGAACC", "CCAGACACAGACTTAGACTG"},
	barcoding.DualBarcode{"B13", "GCGGAAGCGCAAGCCTAAGC", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"D13", "TAAGCCGAAGCCCAACAACA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"F13", "ACATGAACATCAACAGTAAC", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"H13", "CGAGAACGACAACGTTAACG", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"J13", "TAACGTGAACGTCAACGGTA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"L13", "CGGTAACGGGAACGGCAACG", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"N13", "CAACGCTAACGCGAACGCCA", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"P13", "CGCCAACCATAACCAGAACC", "GACTGAGACTCAGACGTAGA"},
	barcoding.DualBarcode{"B14", "GCGGAAGCGCAAGCCTAAGC", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"D14", "TAAGCCGAAGCCCAACAACA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"F14", "ACATGAACATCAACAGTAAC", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"H14", "CGAGAACGACAACGTTAACG", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"J14", "TAACGTGAACGTCAACGGTA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"L14", "CGGTAACGGGAACGGCAACG", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"N14", "CAACGCTAACGCGAACGCCA", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"P14", "CGCCAACCATAACCAGAACC", "GTAGACGGAGACGCAGACCT"},
	barcoding.DualBarcode{"B15", "GCGGAAGCGCAAGCCTAAGC", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"D15", "TAAGCCGAAGCCCAACAACA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"F15", "ACATGAACATCAACAGTAAC", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"H15", "CGAGAACGACAACGTTAACG", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"J15", "TAACGTGAACGTCAACGGTA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"L15", "CGGTAACGGGAACGGCAACG", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"N15", "CAACGCTAACGCGAACGCCA", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"P15", "CGCCAACCATAACCAGAACC", "GACCTAGACCGAGACCCAGT"},
	barcoding.DualBarcode{"B16", "GCGGAAGCGCAAGCCTAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"D16", "TAAGCCGAAGCCCAACAACA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"F16", "ACATGAACATCAACAGTAAC", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"H16", "CGAGAACGACAACGTTAACG", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"J16", "TAACGTGAACGTCAACGGTA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"L16", "CGGTAACGGGAACGGCAACG", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"N16", "CAACGCTAACGCGAACGCCA", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"P16", "CGCCAACCATAACCAGAACC", "CCAGTAGTAGGAGTAGCAGT"},
	barcoding.DualBarcode{"B17", "GCGGAAGCGCAAGCCTAAGC", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"D17", "TAAGCCGAAGCCCAACAACA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"F17", "ACATGAACATCAACAGTAAC", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"H17", "CGAGAACGACAACGTTAACG", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"J17", "TAACGTGAACGTCAACGGTA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"L17", "CGGTAACGGGAACGGCAACG", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"N17", "CAACGCTAACGCGAACGCCA", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"P17", "CGCCAACCATAACCAGAACC", "GCAGTACTAGTACGAGTACC"},
	barcoding.DualBarcode{"B18", "GCGGAAGCGCAAGCCTAAGC", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"D18", "TAAGCCGAAGCCCAACAACA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"F18", "ACATGAACATCAACAGTAAC", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"H18", "CGAGAACGACAACGTTAACG", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"J18", "TAACGTGAACGTCAACGGTA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"L18", "CGGTAACGGGAACGGCAACG", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"N18", "CAACGCTAACGCGAACGCCA", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"P18", "CGCCAACCATAACCAGAACC", "GTACCAGTTACAGTTTTAGT"},
	barcoding.DualBarcode{"B19", "GCGGAAGCGCAAGCCTAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"D19", "TAAGCCGAAGCCCAACAACA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"F19", "ACATGAACATCAACAGTAAC", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"H19", "CGAGAACGACAACGTTAACG", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"J19", "TAACGTGAACGTCAACGGTA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"L19", "CGGTAACGGGAACGGCAACG", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"N19", "CAACGCTAACGCGAACGCCA", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"P19", "CGCCAACCATAACCAGAACC", "AGTTTGAGTTTCAGTTGTAG"},
	barcoding.DualBarcode{"B20", "GCGGAAGCGCAAGCCTAAGC", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"D20", "TAAGCCGAAGCCCAACAACA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"F20", "ACATGAACATCAACAGTAAC", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"H20", "CGAGAACGACAACGTTAACG", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"J20", "TAACGTGAACGTCAACGGTA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"L20", "CGGTAACGGGAACGGCAACG", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"N20", "CAACGCTAACGCGAACGCCA", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"P20", "CGCCAACCATAACCAGAACC", "GTTCCAGTGACAGTGTTAGT"},
	barcoding.DualBarcode{"B21", "GCGGAAGCGCAAGCCTAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"D21", "TAAGCCGAAGCCCAACAACA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"F21", "ACATGAACATCAACAGTAAC", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"H21", "CGAGAACGACAACGTTAACG", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"J21", "TAACGTGAACGTCAACGGTA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"L21", "CGGTAACGGGAACGGCAACG", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"N21", "CAACGCTAACGCGAACGCCA", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"P21", "CGCCAACCATAACCAGAACC", "TTAGTGTGAGTGTCAGTGGT"},
	barcoding.DualBarcode{"B22", "GCGGAAGCGCAAGCCTAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"D22", "TAAGCCGAAGCCCAACAACA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"F22", "ACATGAACATCAACAGTAAC", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"H22", "CGAGAACGACAACGTTAACG", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"J22", "TAACGTGAACGTCAACGGTA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"L22", "CGGTAACGGGAACGGCAACG", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"N22", "CAACGCTAACGCGAACGCCA", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"P22", "CGCCAACCATAACCAGAACC", "GTGGTAGTGGGAGTGGCAGT"},
	barcoding.DualBarcode{"B23", "GCGGAAGCGCAAGCCTAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"D23", "TAAGCCGAAGCCCAACAACA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"F23", "ACATGAACATCAACAGTAAC", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"H23", "CGAGAACGACAACGTTAACG", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"J23", "TAACGTGAACGTCAACGGTA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"L23", "CGGTAACGGGAACGGCAACG", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"N23", "CAACGCTAACGCGAACGCCA", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"P23", "CGCCAACCATAACCAGAACC", "GCAGTGCTAGTGCGAGTGCC"},
	barcoding.DualBarcode{"B24", "GCGGAAGCGCAAGCCTAAGC", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"D24", "TAAGCCGAAGCCCAACAACA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"F24", "ACATGAACATCAACAGTAAC", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"H24", "CGAGAACGACAACGTTAACG", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"J24", "TAACGTGAACGTCAACGGTA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"L24", "CGGTAACGGGAACGGCAACG", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"N24", "CAACGCTAACGCGAACGCCA", "GTGCCAGTCACAGTCTTAGT"},
	barcoding.DualBarcode{"P24", "CGCCAACCATAACCAGAACC", "GTGCCAGTCACAGTCTTAGT"},
})

func TestPrimerEdgeRegression(t *testing.T) {
	// This is handling a case we commonly see where the barcode is hanging off the edge of the sequence.
	barcoding.ScoreMagicNumber = 25
	seq := "TATGTGTAACCTACTTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTTGGATATGCATATCTATATCGGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGCGTTCTCGCGCACCTGCACCAGTCAGTAAAACGACGGCCAGTGACTTGGTCTCAAAGAAGGCACTGATGCGCTACGAGGACGTGTACATGCCGGAGGTGTACAAGGCAATCAACATCGCACAGAACACGGCATGGAAGATCAACAAGAAGGTGCTGGCAGTGGCAAACGTGATCACGAAGTGGAAGCACTGCCCGGTGGAGGACATCCCGGCAATCATCCGCGAGGAGCTGCCGATGAAGCCGGAGGACATCGACATGAACCCGGAGGCACTGACGGCATGGAAGCGCGCAGCAGCAGCAGTGTACCGCAAGGACGTGGCACGCAAGGCACAGCGCATCTCGCTGGAGTTCATGCTGGAGCAGGCAAACAAGTTCGCAAACTCGAAGAAGATGGTTCCCGTACAACATGGACTGGCGCGGTCGCGTGTACGCAGTGTCGGAGTTCAACCCGCAGGGTAACGACATGACGAAGGGTCTGCTGACGCTGGCAAAGTTCAAGCCGATCGGTGGTGAGGGTGACTACTGGCTGAAGATCCACGGTGCAGACTGCGCAGGTGTGCCGAAGTTCATGCGAGCGCATCAAGTTCATCGAGGAAAACCGCAGAACATCATGGCATGCGCAAAGTCGCCGCTGGAGGCAACGTGGTGGGCAGAGCAGGACTCGCCGTTCTGCTTCAACGCATTCTGCTTCGGTGCGCAGGTCGCAGAACCACGGTCTGTCGTACAACTGCTCGCTGCCGCCGGCATCGACGGTTCGTGCTCGGGTATCCAGCACTTCTCGGCAATGCTGACGGACGAGGTGGGTGGTCGCGCAGTGAACCTGCTGCCGTCGGAGACGGTGCAGGACATCTACGGTATCGTGGCAAAGAAGGTGAACGAGATCCTGCAGGCAGACGCAATCAACGGTACGGACAACGAGGTGGTGACGGTGACGGACGAGAACACGGGTGAGACGAGACCAAGTCGTCATAGCTGTTTCCTGAGAGCTTGGCAGGTGATGACTGTGCTTCTG"
	well, _ := barcoding.DualBarcodeSequence(seq, "gtcatcacctgccaagctct", "gggttattgtctcatgagcgg", Barcodes)
	if well != "K5" {
		t.Errorf("Should have matched K5")
	}
}
