/*
Package barcoding contains functions to help barcode sequencing data.

DNA barcoding is a strategy during DNA sequencing to correlate reads to certain
samples. Modern DNA sequencers sequence a lot of DNA, and often you'll want to
split up one DNA sequencer flow cell to sequence a bunch of different samples.
However, you need a way to tell the samples apart. This is usually done with
DNA barcodes - you attach a barcode to all the sequences from a certain sample,
then use software after sequencing to sort out barcoded samples.

Normally, vendor software handles barcoding for you (for example, Oxford
Nanopore's MinKNOW app). However, specialized barcoding strategies can be used
for more advanced sample processing.
*/

package barcoding

import (
	"encoding/csv"
	"io"
	"sort"
	"strings"

	"github.com/koeng101/dnadesign/lib/align"
	"github.com/koeng101/dnadesign/lib/align/matrix"
	"github.com/koeng101/dnadesign/lib/alphabet"
	"github.com/koeng101/dnadesign/lib/transform"
)

// ScoreMagicNumber is the SmithWaterman score needed to match a barcode. 28 is
// chosen as a magic number that fits pretty well with normal 40bp barcodes.
// (20bp primer + 20bp barcode)
var ScoreMagicNumber = 28

// MinimalReadSize is the minimal size of reads needed to barcode. This is
// mostly important for Nanopore reads, since amplicon Nanopore sequencing
// tends to generate quite a few small reads from PCR products that we do not
// want to barcode.
var MinimalReadSize = 200

// EdgeCheckSize is how long to check from the edge of both sides of a read.
// This is important because SmithWaterman alignment, used for aligning
// barcodes, is a quadratic algorithm. Nanopore sequencing prep, especially
// ligation preparation, can add DNA to either end of an amplicon. The native
// barcode (NB) and native adapter (NA) sequence may or may not be on both
// sides, adding ~80bp to the read.
var EdgeCheckSize = 120

/******************************************************************************
Feb 12, 2024
                            Dual barcodes

When using Nanopore sequencing, I can barcode both sides of a given sequence.
Dual barcodes can encode a combinatorial quantity of potential sequences, so
are nice for barcoding lots of different DNA wells at once.

I personally use this for plasmid sequencing.

Keoni
******************************************************************************/

// DualBarcodePrimerSet represents a list of dual-barcoded wells in a
// convenient format.
type DualBarcodePrimerSet struct {
	BarcodeMap        map[string]DualBarcode
	ReverseBarcodeMap map[DualBarcode]string
	ForwardBarcodes   []string
	ReverseBarcodes   []string
}

// DualBarcode contains a forward and reverse barcode.
type DualBarcode struct {
	Name    string
	Forward string
	Reverse string
}

// DualBarcodesToPrimerSet parsers a list of dual barcodes into a dual barcode
// primer set.
func DualBarcodesToPrimerSet(dualBarcodes []DualBarcode) DualBarcodePrimerSet {
	var result DualBarcodePrimerSet
	result.BarcodeMap = make(map[string]DualBarcode)
	result.ReverseBarcodeMap = make(map[DualBarcode]string)
	forwardBarcodesMap := make(map[string]bool)
	reverseBarcodesMap := make(map[string]bool)

	for _, barcode := range dualBarcodes {
		forwardBarcodesMap[barcode.Forward] = true
		reverseBarcodesMap[barcode.Reverse] = true
		newDualBarcode := DualBarcode{Forward: barcode.Forward, Reverse: barcode.Reverse}
		result.BarcodeMap[barcode.Name] = newDualBarcode
		result.ReverseBarcodeMap[newDualBarcode] = barcode.Name
	}
	// Convert maps to slices
	forwardBarcodes := make([]string, 0, len(forwardBarcodesMap))
	for barcode := range forwardBarcodesMap {
		forwardBarcodes = append(forwardBarcodes, barcode)
	}
	reverseBarcodes := make([]string, 0, len(reverseBarcodesMap))
	for barcode := range reverseBarcodesMap {
		reverseBarcodes = append(reverseBarcodes, barcode)
	}

	// Sort the slices
	sort.Strings(forwardBarcodes)
	sort.Strings(reverseBarcodes)

	// Append sorted barcodes to result
	result.ForwardBarcodes = forwardBarcodes
	result.ReverseBarcodes = reverseBarcodes

	return result
}

// ParseDualPrimerSet parses a csv file into a DualBarcodePrimerSet.
func ParseDualPrimerSet(csvFile io.Reader) (DualBarcodePrimerSet, error) {
	var result DualBarcodePrimerSet
	result.BarcodeMap = make(map[string]DualBarcode)
	result.ReverseBarcodeMap = make(map[DualBarcode]string)
	forwardBarcodesMap := make(map[string]bool)
	reverseBarcodesMap := make(map[string]bool)

	// Create a new CSV reader reading from the input io.Reader
	reader := csv.NewReader(csvFile)

	for {
		// Read each record from csv
		record, err := reader.Read()
		// Break the loop at the end of the file
		if err == io.EOF {
			break
		}
		// Handle any other error
		if err != nil {
			return result, err
		}
		if len(record) == 3 {
			well := record[0]
			forwardBarcode := record[1]
			reverseBarcode := record[2]

			forwardBarcodesMap[forwardBarcode] = true
			reverseBarcodesMap[reverseBarcode] = true
			newDualBarcode := DualBarcode{Forward: forwardBarcode, Reverse: reverseBarcode}
			result.BarcodeMap[well] = newDualBarcode
			result.ReverseBarcodeMap[newDualBarcode] = well
		}
	}

	// Convert maps to slices
	forwardBarcodes := make([]string, 0, len(forwardBarcodesMap))
	for barcode := range forwardBarcodesMap {
		forwardBarcodes = append(forwardBarcodes, barcode)
	}
	reverseBarcodes := make([]string, 0, len(reverseBarcodesMap))
	for barcode := range reverseBarcodesMap {
		reverseBarcodes = append(reverseBarcodes, barcode)
	}

	// Sort the slices
	sort.Strings(forwardBarcodes)
	sort.Strings(reverseBarcodes)

	// Append sorted barcodes to result
	result.ForwardBarcodes = forwardBarcodes
	result.ReverseBarcodes = reverseBarcodes

	return result, nil
}

// DualBarcodeSequence analyzes a sequence for both a forward and reverse
// barcode pair and returns their well.
func DualBarcodeSequence(sequence string, forwardPrimer string, reversePrimer string, primerSet DualBarcodePrimerSet) (string, error) {
	m := [][]int{
		/*       A C G T U */
		/* A */ {1, -1, -1, -1, -1},
		/* C */ {-1, 1, -1, -1, -1},
		/* G */ {-1, -1, 1, -1, -1},
		/* T */ {-1, -1, -1, 1, -1},
		/* U */ {-1, -1, -1, -1, 1},
	}

	alphabet := alphabet.NewAlphabet([]string{"A", "C", "G", "T", "U"})
	subMatrix, _ := matrix.NewSubstitutionMatrix(alphabet, alphabet, m)
	scoring, _ := align.NewScoring(subMatrix, -1)

	if len(sequence) < MinimalReadSize {
		return "", nil
	}
	forwardPrimer = strings.ToUpper(forwardPrimer)
	reversePrimer = strings.ToUpper(reversePrimer)
	sequence = strings.ToUpper(sequence) // make sure sequence is upper case for the purposes of barcoding
	sequenceForward := sequence[:EdgeCheckSize]
	sequenceReverse := sequence[len(sequence)-EdgeCheckSize:]
	var topRankedForward string
	var topRankedForwardScore int
	var topRankedReverse string
	var topRankedReverseScore int
	// We want to check both ends for barcodes
	for _, sequence := range []string{sequenceForward, sequenceReverse} {
		for _, forwardBarcode := range primerSet.ForwardBarcodes {
			// We check both the barcode's sequence and its reverse complement.
			scoreFwd, _, _, err := align.SmithWaterman(sequence, forwardBarcode+forwardPrimer, scoring)
			if err != nil {
				return "", err
			}
			complementScoreFwd, _, _, err := align.SmithWaterman(sequence, transform.ReverseComplement(forwardBarcode+forwardPrimer), scoring)
			if err != nil {
				return "", err
			}

			// If the score is greater than any previous score and above the magic
			// number, replace the topRankedScore and continue on!
			switch {
			case scoreFwd > topRankedForwardScore && scoreFwd > ScoreMagicNumber:
				topRankedForward = forwardBarcode
				topRankedForwardScore = scoreFwd
			case complementScoreFwd > topRankedForwardScore && complementScoreFwd > ScoreMagicNumber:
				topRankedForward = forwardBarcode
				topRankedForwardScore = complementScoreFwd
			}

		}
		for _, reverseBarcode := range primerSet.ReverseBarcodes {
			scoreRev, _, _, err := align.SmithWaterman(sequence, reverseBarcode+reversePrimer, scoring)
			if err != nil {
				return "", err
			}

			complementScoreRev, _, _, err := align.SmithWaterman(sequence, transform.ReverseComplement(reverseBarcode+reversePrimer), scoring)
			if err != nil {
				return "", err
			}

			switch {
			case scoreRev > topRankedReverseScore && scoreRev > ScoreMagicNumber:
				topRankedReverse = reverseBarcode
				topRankedReverseScore = scoreRev
			case complementScoreRev > topRankedReverseScore && complementScoreRev > ScoreMagicNumber:
				topRankedReverse = reverseBarcode
				topRankedReverseScore = complementScoreRev
			}
		}
	}
	// This is to handle the case that we did not find a barcode
	// Finally, get the well from the barcode map.
	well := primerSet.ReverseBarcodeMap[DualBarcode{Forward: topRankedForward, Reverse: topRankedReverse}]
	return well, nil
}

var DefaultBarcodes = DualBarcodesToPrimerSet([]DualBarcode{
	DualBarcode{"A1", "GGAAAAGCAAAACTAAAACG", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"C1", "GAAGGACAAGGTTAAGGTGA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"E1", "GGTGAAGGTCAAGGGTAAGG", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"G1", "TAAGGGGAAGGGCAAGGCTA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"I1", "GGCTAAGGCGAAGGCCAAGC", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"K1", "CAAGCATAAGCAGAAGCACA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"M1", "GCACAAGCTTAAGCTGAAGC", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"O1", "GAAGCTCAAGCGTAAGCGGA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"A2", "GGAAAAGCAAAACTAAAACG", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"C2", "GAAGGACAAGGTTAAGGTGA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"E2", "GGTGAAGGTCAAGGGTAAGG", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"G2", "TAAGGGGAAGGGCAAGGCTA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"I2", "GGCTAAGGCGAAGGCCAAGC", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"K2", "CAAGCATAAGCAGAAGCACA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"M2", "GCACAAGCTTAAGCTGAAGC", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"O2", "GAAGCTCAAGCGTAAGCGGA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"A3", "GGAAAAGCAAAACTAAAACG", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"C3", "GAAGGACAAGGTTAAGGTGA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"E3", "GGTGAAGGTCAAGGGTAAGG", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"G3", "TAAGGGGAAGGGCAAGGCTA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"I3", "GGCTAAGGCGAAGGCCAAGC", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"K3", "CAAGCATAAGCAGAAGCACA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"M3", "GCACAAGCTTAAGCTGAAGC", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"O3", "GAAGCTCAAGCGTAAGCGGA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"A4", "GGAAAAGCAAAACTAAAACG", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"C4", "GAAGGACAAGGTTAAGGTGA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"E4", "GGTGAAGGTCAAGGGTAAGG", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"G4", "TAAGGGGAAGGGCAAGGCTA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"I4", "GGCTAAGGCGAAGGCCAAGC", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"K4", "CAAGCATAAGCAGAAGCACA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"M4", "GCACAAGCTTAAGCTGAAGC", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"O4", "GAAGCTCAAGCGTAAGCGGA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"A5", "GGAAAAGCAAAACTAAAACG", "GGATATGCATATCTATATCG"},
	DualBarcode{"C5", "GAAGGACAAGGTTAAGGTGA", "GGATATGCATATCTATATCG"},
	DualBarcode{"E5", "GGTGAAGGTCAAGGGTAAGG", "GGATATGCATATCTATATCG"},
	DualBarcode{"G5", "TAAGGGGAAGGGCAAGGCTA", "GGATATGCATATCTATATCG"},
	DualBarcode{"I5", "GGCTAAGGCGAAGGCCAAGC", "GGATATGCATATCTATATCG"},
	DualBarcode{"K5", "CAAGCATAAGCAGAAGCACA", "GGATATGCATATCTATATCG"},
	DualBarcode{"M5", "GCACAAGCTTAAGCTGAAGC", "GGATATGCATATCTATATCG"},
	DualBarcode{"O5", "GAAGCTCAAGCGTAAGCGGA", "GGATATGCATATCTATATCG"},
	DualBarcode{"A6", "GGAAAAGCAAAACTAAAACG", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"C6", "GAAGGACAAGGTTAAGGTGA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"E6", "GGTGAAGGTCAAGGGTAAGG", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"G6", "TAAGGGGAAGGGCAAGGCTA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"I6", "GGCTAAGGCGAAGGCCAAGC", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"K6", "CAAGCATAAGCAGAAGCACA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"M6", "GCACAAGCTTAAGCTGAAGC", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"O6", "GAAGCTCAAGCGTAAGCGGA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"A7", "GGAAAAGCAAAACTAAAACG", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"C7", "GAAGGACAAGGTTAAGGTGA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"E7", "GGTGAAGGTCAAGGGTAAGG", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"G7", "TAAGGGGAAGGGCAAGGCTA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"I7", "GGCTAAGGCGAAGGCCAAGC", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"K7", "CAAGCATAAGCAGAAGCACA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"M7", "GCACAAGCTTAAGCTGAAGC", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"O7", "GAAGCTCAAGCGTAAGCGGA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"A8", "GGAAAAGCAAAACTAAAACG", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"C8", "GAAGGACAAGGTTAAGGTGA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"E8", "GGTGAAGGTCAAGGGTAAGG", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"G8", "TAAGGGGAAGGGCAAGGCTA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"I8", "GGCTAAGGCGAAGGCCAAGC", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"K8", "CAAGCATAAGCAGAAGCACA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"M8", "GCACAAGCTTAAGCTGAAGC", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"O8", "GAAGCTCAAGCGTAAGCGGA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"A9", "GGAAAAGCAAAACTAAAACG", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"C9", "GAAGGACAAGGTTAAGGTGA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"E9", "GGTGAAGGTCAAGGGTAAGG", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"G9", "TAAGGGGAAGGGCAAGGCTA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"I9", "GGCTAAGGCGAAGGCCAAGC", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"K9", "CAAGCATAAGCAGAAGCACA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"M9", "GCACAAGCTTAAGCTGAAGC", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"O9", "GAAGCTCAAGCGTAAGCGGA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"A10", "GGAAAAGCAAAACTAAAACG", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"C10", "GAAGGACAAGGTTAAGGTGA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"E10", "GGTGAAGGTCAAGGGTAAGG", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"G10", "TAAGGGGAAGGGCAAGGCTA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"I10", "GGCTAAGGCGAAGGCCAAGC", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"K10", "CAAGCATAAGCAGAAGCACA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"M10", "GCACAAGCTTAAGCTGAAGC", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"O10", "GAAGCTCAAGCGTAAGCGGA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"A11", "GGAAAAGCAAAACTAAAACG", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"C11", "GAAGGACAAGGTTAAGGTGA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"E11", "GGTGAAGGTCAAGGGTAAGG", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"G11", "TAAGGGGAAGGGCAAGGCTA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"I11", "GGCTAAGGCGAAGGCCAAGC", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"K11", "CAAGCATAAGCAGAAGCACA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"M11", "GCACAAGCTTAAGCTGAAGC", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"O11", "GAAGCTCAAGCGTAAGCGGA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"A12", "GGAAAAGCAAAACTAAAACG", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"C12", "GAAGGACAAGGTTAAGGTGA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"E12", "GGTGAAGGTCAAGGGTAAGG", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"G12", "TAAGGGGAAGGGCAAGGCTA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"I12", "GGCTAAGGCGAAGGCCAAGC", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"K12", "CAAGCATAAGCAGAAGCACA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"M12", "GCACAAGCTTAAGCTGAAGC", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"O12", "GAAGCTCAAGCGTAAGCGGA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"A13", "GGAAAAGCAAAACTAAAACG", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"C13", "GAAGGACAAGGTTAAGGTGA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"E13", "GGTGAAGGTCAAGGGTAAGG", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"G13", "TAAGGGGAAGGGCAAGGCTA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"I13", "GGCTAAGGCGAAGGCCAAGC", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"K13", "CAAGCATAAGCAGAAGCACA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"M13", "GCACAAGCTTAAGCTGAAGC", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"O13", "GAAGCTCAAGCGTAAGCGGA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"A14", "GGAAAAGCAAAACTAAAACG", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"C14", "GAAGGACAAGGTTAAGGTGA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"E14", "GGTGAAGGTCAAGGGTAAGG", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"G14", "TAAGGGGAAGGGCAAGGCTA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"I14", "GGCTAAGGCGAAGGCCAAGC", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"K14", "CAAGCATAAGCAGAAGCACA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"M14", "GCACAAGCTTAAGCTGAAGC", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"O14", "GAAGCTCAAGCGTAAGCGGA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"A15", "GGAAAAGCAAAACTAAAACG", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"C15", "GAAGGACAAGGTTAAGGTGA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"E15", "GGTGAAGGTCAAGGGTAAGG", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"G15", "TAAGGGGAAGGGCAAGGCTA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"I15", "GGCTAAGGCGAAGGCCAAGC", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"K15", "CAAGCATAAGCAGAAGCACA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"M15", "GCACAAGCTTAAGCTGAAGC", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"O15", "GAAGCTCAAGCGTAAGCGGA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"A16", "GGAAAAGCAAAACTAAAACG", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"C16", "GAAGGACAAGGTTAAGGTGA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"E16", "GGTGAAGGTCAAGGGTAAGG", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"G16", "TAAGGGGAAGGGCAAGGCTA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"I16", "GGCTAAGGCGAAGGCCAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"K16", "CAAGCATAAGCAGAAGCACA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"M16", "GCACAAGCTTAAGCTGAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"O16", "GAAGCTCAAGCGTAAGCGGA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"A17", "GGAAAAGCAAAACTAAAACG", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"C17", "GAAGGACAAGGTTAAGGTGA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"E17", "GGTGAAGGTCAAGGGTAAGG", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"G17", "TAAGGGGAAGGGCAAGGCTA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"I17", "GGCTAAGGCGAAGGCCAAGC", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"K17", "CAAGCATAAGCAGAAGCACA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"M17", "GCACAAGCTTAAGCTGAAGC", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"O17", "GAAGCTCAAGCGTAAGCGGA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"A18", "GGAAAAGCAAAACTAAAACG", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"C18", "GAAGGACAAGGTTAAGGTGA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"E18", "GGTGAAGGTCAAGGGTAAGG", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"G18", "TAAGGGGAAGGGCAAGGCTA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"I18", "GGCTAAGGCGAAGGCCAAGC", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"K18", "CAAGCATAAGCAGAAGCACA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"M18", "GCACAAGCTTAAGCTGAAGC", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"O18", "GAAGCTCAAGCGTAAGCGGA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"A19", "GGAAAAGCAAAACTAAAACG", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"C19", "GAAGGACAAGGTTAAGGTGA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"E19", "GGTGAAGGTCAAGGGTAAGG", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"G19", "TAAGGGGAAGGGCAAGGCTA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"I19", "GGCTAAGGCGAAGGCCAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"K19", "CAAGCATAAGCAGAAGCACA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"M19", "GCACAAGCTTAAGCTGAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"O19", "GAAGCTCAAGCGTAAGCGGA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"A20", "GGAAAAGCAAAACTAAAACG", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"C20", "GAAGGACAAGGTTAAGGTGA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"E20", "GGTGAAGGTCAAGGGTAAGG", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"G20", "TAAGGGGAAGGGCAAGGCTA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"I20", "GGCTAAGGCGAAGGCCAAGC", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"K20", "CAAGCATAAGCAGAAGCACA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"M20", "GCACAAGCTTAAGCTGAAGC", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"O20", "GAAGCTCAAGCGTAAGCGGA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"A21", "GGAAAAGCAAAACTAAAACG", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"C21", "GAAGGACAAGGTTAAGGTGA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"E21", "GGTGAAGGTCAAGGGTAAGG", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"G21", "TAAGGGGAAGGGCAAGGCTA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"I21", "GGCTAAGGCGAAGGCCAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"K21", "CAAGCATAAGCAGAAGCACA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"M21", "GCACAAGCTTAAGCTGAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"O21", "GAAGCTCAAGCGTAAGCGGA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"A22", "GGAAAAGCAAAACTAAAACG", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"C22", "GAAGGACAAGGTTAAGGTGA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"E22", "GGTGAAGGTCAAGGGTAAGG", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"G22", "TAAGGGGAAGGGCAAGGCTA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"I22", "GGCTAAGGCGAAGGCCAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"K22", "CAAGCATAAGCAGAAGCACA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"M22", "GCACAAGCTTAAGCTGAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"O22", "GAAGCTCAAGCGTAAGCGGA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"A23", "GGAAAAGCAAAACTAAAACG", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"C23", "GAAGGACAAGGTTAAGGTGA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"E23", "GGTGAAGGTCAAGGGTAAGG", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"G23", "TAAGGGGAAGGGCAAGGCTA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"I23", "GGCTAAGGCGAAGGCCAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"K23", "CAAGCATAAGCAGAAGCACA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"M23", "GCACAAGCTTAAGCTGAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"O23", "GAAGCTCAAGCGTAAGCGGA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"A24", "GGAAAAGCAAAACTAAAACG", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"C24", "GAAGGACAAGGTTAAGGTGA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"E24", "GGTGAAGGTCAAGGGTAAGG", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"G24", "TAAGGGGAAGGGCAAGGCTA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"I24", "GGCTAAGGCGAAGGCCAAGC", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"K24", "CAAGCATAAGCAGAAGCACA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"M24", "GCACAAGCTTAAGCTGAAGC", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"O24", "GAAGCTCAAGCGTAAGCGGA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"B1", "GCGGAAGCGCAAGCCTAAGC", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"D1", "TAAGCCGAAGCCCAACAACA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"F1", "ACATGAACATCAACAGTAAC", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"H1", "CGAGAACGACAACGTTAACG", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"J1", "TAACGTGAACGTCAACGGTA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"L1", "CGGTAACGGGAACGGCAACG", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"N1", "CAACGCTAACGCGAACGCCA", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"P1", "CGCCAACCATAACCAGAACC", "GAACCACAACCTTAACCTGA"},
	DualBarcode{"B2", "GCGGAAGCGCAAGCCTAAGC", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"D2", "TAAGCCGAAGCCCAACAACA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"F2", "ACATGAACATCAACAGTAAC", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"H2", "CGAGAACGACAACGTTAACG", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"J2", "TAACGTGAACGTCAACGGTA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"L2", "CGGTAACGGGAACGGCAACG", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"N2", "CAACGCTAACGCGAACGCCA", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"P2", "CGCCAACCATAACCAGAACC", "CCTGAACCTCAACCGTAACC"},
	DualBarcode{"B3", "GCGGAAGCGCAAGCCTAAGC", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"D3", "TAAGCCGAAGCCCAACAACA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"F3", "ACATGAACATCAACAGTAAC", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"H3", "CGAGAACGACAACGTTAACG", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"J3", "TAACGTGAACGTCAACGGTA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"L3", "CGGTAACGGGAACGGCAACG", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"N3", "CAACGCTAACGCGAACGCCA", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"P3", "CGCCAACCATAACCAGAACC", "TAACCGGAACCGCAACCCTA"},
	DualBarcode{"B4", "GCGGAAGCGCAAGCCTAAGC", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"D4", "TAAGCCGAAGCCCAACAACA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"F4", "ACATGAACATCAACAGTAAC", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"H4", "CGAGAACGACAACGTTAACG", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"J4", "TAACGTGAACGTCAACGGTA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"L4", "CGGTAACGGGAACGGCAACG", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"N4", "CAACGCTAACGCGAACGCCA", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"P4", "CGCCAACCATAACCAGAACC", "CCCTAACCCGAACCCCATAT"},
	DualBarcode{"B5", "GCGGAAGCGCAAGCCTAAGC", "GGATATGCATATCTATATCG"},
	DualBarcode{"D5", "TAAGCCGAAGCCCAACAACA", "GGATATGCATATCTATATCG"},
	DualBarcode{"F5", "ACATGAACATCAACAGTAAC", "GGATATGCATATCTATATCG"},
	DualBarcode{"H5", "CGAGAACGACAACGTTAACG", "GGATATGCATATCTATATCG"},
	DualBarcode{"J5", "TAACGTGAACGTCAACGGTA", "GGATATGCATATCTATATCG"},
	DualBarcode{"L5", "CGGTAACGGGAACGGCAACG", "GGATATGCATATCTATATCG"},
	DualBarcode{"N5", "CAACGCTAACGCGAACGCCA", "GGATATGCATATCTATATCG"},
	DualBarcode{"P5", "CGCCAACCATAACCAGAACC", "GGATATGCATATCTATATCG"},
	DualBarcode{"B6", "GCGGAAGCGCAAGCCTAAGC", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"D6", "TAAGCCGAAGCCCAACAACA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"F6", "ACATGAACATCAACAGTAAC", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"H6", "CGAGAACGACAACGTTAACG", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"J6", "TAACGTGAACGTCAACGGTA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"L6", "CGGTAACGGGAACGGCAACG", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"N6", "CAACGCTAACGCGAACGCCA", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"P6", "CGCCAACCATAACCAGAACC", "CGTATGCGGATGCGCATGCC"},
	DualBarcode{"B7", "GCGGAAGCGCAAGCCTAAGC", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"D7", "TAAGCCGAAGCCCAACAACA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"F7", "ACATGAACATCAACAGTAAC", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"H7", "CGAGAACGACAACGTTAACG", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"J7", "TAACGTGAACGTCAACGGTA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"L7", "CGGTAACGGGAACGGCAACG", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"N7", "CAACGCTAACGCGAACGCCA", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"P7", "CGCCAACCATAACCAGAACC", "ATGCCTATGCCGATGCCCAT"},
	DualBarcode{"B8", "GCGGAAGCGCAAGCCTAAGC", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"D8", "TAAGCCGAAGCCCAACAACA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"F8", "ACATGAACATCAACAGTAAC", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"H8", "CGAGAACGACAACGTTAACG", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"J8", "TAACGTGAACGTCAACGGTA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"L8", "CGGTAACGGGAACGGCAACG", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"N8", "CAACGCTAACGCGAACGCCA", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"P8", "CGCCAACCATAACCAGAACC", "CCCATCATCAGTATCAGGAT"},
	DualBarcode{"B9", "GCGGAAGCGCAAGCCTAAGC", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"D9", "TAAGCCGAAGCCCAACAACA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"F9", "ACATGAACATCAACAGTAAC", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"H9", "CGAGAACGACAACGTTAACG", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"J9", "TAACGTGAACGTCAACGGTA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"L9", "CGGTAACGGGAACGGCAACG", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"N9", "CAACGCTAACGCGAACGCCA", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"P9", "CGCCAACCATAACCAGAACC", "AGGATCAGCATCACTATCAC"},
	DualBarcode{"B10", "GCGGAAGCGCAAGCCTAAGC", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"D10", "TAAGCCGAAGCCCAACAACA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"F10", "ACATGAACATCAACAGTAAC", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"H10", "CGAGAACGACAACGTTAACG", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"J10", "TAACGTGAACGTCAACGGTA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"L10", "CGGTAACGGGAACGGCAACG", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"N10", "CAACGCTAACGCGAACGCCA", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"P10", "CGCCAACCATAACCAGAACC", "ATCACGATCACCATCTAGAT"},
	DualBarcode{"B11", "GCGGAAGCGCAAGCCTAAGC", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"D11", "TAAGCCGAAGCCCAACAACA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"F11", "ACATGAACATCAACAGTAAC", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"H11", "CGAGAACGACAACGTTAACG", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"J11", "TAACGTGAACGTCAACGGTA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"L11", "CGGTAACGGGAACGGCAACG", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"N11", "CAACGCTAACGCGAACGCCA", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"P11", "CGCCAACCATAACCAGAACC", "TCTTGATCTTCATCTGTATC"},
	DualBarcode{"B12", "GCGGAAGCGCAAGCCTAAGC", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"D12", "TAAGCCGAAGCCCAACAACA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"F12", "ACATGAACATCAACAGTAAC", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"H12", "CGAGAACGACAACGTTAACG", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"J12", "TAACGTGAACGTCAACGGTA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"L12", "CGGTAACGGGAACGGCAACG", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"N12", "CAACGCTAACGCGAACGCCA", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"P12", "CGCCAACCATAACCAGAACC", "CCAGACACAGACTTAGACTG"},
	DualBarcode{"B13", "GCGGAAGCGCAAGCCTAAGC", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"D13", "TAAGCCGAAGCCCAACAACA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"F13", "ACATGAACATCAACAGTAAC", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"H13", "CGAGAACGACAACGTTAACG", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"J13", "TAACGTGAACGTCAACGGTA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"L13", "CGGTAACGGGAACGGCAACG", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"N13", "CAACGCTAACGCGAACGCCA", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"P13", "CGCCAACCATAACCAGAACC", "GACTGAGACTCAGACGTAGA"},
	DualBarcode{"B14", "GCGGAAGCGCAAGCCTAAGC", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"D14", "TAAGCCGAAGCCCAACAACA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"F14", "ACATGAACATCAACAGTAAC", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"H14", "CGAGAACGACAACGTTAACG", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"J14", "TAACGTGAACGTCAACGGTA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"L14", "CGGTAACGGGAACGGCAACG", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"N14", "CAACGCTAACGCGAACGCCA", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"P14", "CGCCAACCATAACCAGAACC", "GTAGACGGAGACGCAGACCT"},
	DualBarcode{"B15", "GCGGAAGCGCAAGCCTAAGC", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"D15", "TAAGCCGAAGCCCAACAACA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"F15", "ACATGAACATCAACAGTAAC", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"H15", "CGAGAACGACAACGTTAACG", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"J15", "TAACGTGAACGTCAACGGTA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"L15", "CGGTAACGGGAACGGCAACG", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"N15", "CAACGCTAACGCGAACGCCA", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"P15", "CGCCAACCATAACCAGAACC", "GACCTAGACCGAGACCCAGT"},
	DualBarcode{"B16", "GCGGAAGCGCAAGCCTAAGC", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"D16", "TAAGCCGAAGCCCAACAACA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"F16", "ACATGAACATCAACAGTAAC", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"H16", "CGAGAACGACAACGTTAACG", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"J16", "TAACGTGAACGTCAACGGTA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"L16", "CGGTAACGGGAACGGCAACG", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"N16", "CAACGCTAACGCGAACGCCA", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"P16", "CGCCAACCATAACCAGAACC", "CCAGTAGTAGGAGTAGCAGT"},
	DualBarcode{"B17", "GCGGAAGCGCAAGCCTAAGC", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"D17", "TAAGCCGAAGCCCAACAACA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"F17", "ACATGAACATCAACAGTAAC", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"H17", "CGAGAACGACAACGTTAACG", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"J17", "TAACGTGAACGTCAACGGTA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"L17", "CGGTAACGGGAACGGCAACG", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"N17", "CAACGCTAACGCGAACGCCA", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"P17", "CGCCAACCATAACCAGAACC", "GCAGTACTAGTACGAGTACC"},
	DualBarcode{"B18", "GCGGAAGCGCAAGCCTAAGC", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"D18", "TAAGCCGAAGCCCAACAACA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"F18", "ACATGAACATCAACAGTAAC", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"H18", "CGAGAACGACAACGTTAACG", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"J18", "TAACGTGAACGTCAACGGTA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"L18", "CGGTAACGGGAACGGCAACG", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"N18", "CAACGCTAACGCGAACGCCA", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"P18", "CGCCAACCATAACCAGAACC", "GTACCAGTTACAGTTTTAGT"},
	DualBarcode{"B19", "GCGGAAGCGCAAGCCTAAGC", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"D19", "TAAGCCGAAGCCCAACAACA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"F19", "ACATGAACATCAACAGTAAC", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"H19", "CGAGAACGACAACGTTAACG", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"J19", "TAACGTGAACGTCAACGGTA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"L19", "CGGTAACGGGAACGGCAACG", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"N19", "CAACGCTAACGCGAACGCCA", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"P19", "CGCCAACCATAACCAGAACC", "AGTTTGAGTTTCAGTTGTAG"},
	DualBarcode{"B20", "GCGGAAGCGCAAGCCTAAGC", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"D20", "TAAGCCGAAGCCCAACAACA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"F20", "ACATGAACATCAACAGTAAC", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"H20", "CGAGAACGACAACGTTAACG", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"J20", "TAACGTGAACGTCAACGGTA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"L20", "CGGTAACGGGAACGGCAACG", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"N20", "CAACGCTAACGCGAACGCCA", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"P20", "CGCCAACCATAACCAGAACC", "GTTCCAGTGACAGTGTTAGT"},
	DualBarcode{"B21", "GCGGAAGCGCAAGCCTAAGC", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"D21", "TAAGCCGAAGCCCAACAACA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"F21", "ACATGAACATCAACAGTAAC", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"H21", "CGAGAACGACAACGTTAACG", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"J21", "TAACGTGAACGTCAACGGTA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"L21", "CGGTAACGGGAACGGCAACG", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"N21", "CAACGCTAACGCGAACGCCA", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"P21", "CGCCAACCATAACCAGAACC", "TTAGTGTGAGTGTCAGTGGT"},
	DualBarcode{"B22", "GCGGAAGCGCAAGCCTAAGC", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"D22", "TAAGCCGAAGCCCAACAACA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"F22", "ACATGAACATCAACAGTAAC", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"H22", "CGAGAACGACAACGTTAACG", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"J22", "TAACGTGAACGTCAACGGTA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"L22", "CGGTAACGGGAACGGCAACG", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"N22", "CAACGCTAACGCGAACGCCA", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"P22", "CGCCAACCATAACCAGAACC", "GTGGTAGTGGGAGTGGCAGT"},
	DualBarcode{"B23", "GCGGAAGCGCAAGCCTAAGC", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"D23", "TAAGCCGAAGCCCAACAACA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"F23", "ACATGAACATCAACAGTAAC", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"H23", "CGAGAACGACAACGTTAACG", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"J23", "TAACGTGAACGTCAACGGTA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"L23", "CGGTAACGGGAACGGCAACG", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"N23", "CAACGCTAACGCGAACGCCA", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"P23", "CGCCAACCATAACCAGAACC", "GCAGTGCTAGTGCGAGTGCC"},
	DualBarcode{"B24", "GCGGAAGCGCAAGCCTAAGC", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"D24", "TAAGCCGAAGCCCAACAACA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"F24", "ACATGAACATCAACAGTAAC", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"H24", "CGAGAACGACAACGTTAACG", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"J24", "TAACGTGAACGTCAACGGTA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"L24", "CGGTAACGGGAACGGCAACG", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"N24", "CAACGCTAACGCGAACGCCA", "GTGCCAGTCACAGTCTTAGT"},
	DualBarcode{"P24", "CGCCAACCATAACCAGAACC", "GTGCCAGTCACAGTCTTAGT"},
})
