-- examples/clone_examples.lua
local dnadesign = require("dnadesign")
local clone = dnadesign.clone
local transform = dnadesign.transform

describe("Clone Examples", function()
    it("demonstrates basic restriction enzyme cutting", function()
        -- Using the test case from the Go tests that we know works
        local sequence = {
            sequence = "ATATATA" .. "ATGCAGAGACC" .. "GGTCTCAATGC" .. "ATGCATCGATCGACTAGCATG" .. "ATGCAGAGACC" .. "GGTCTCA",
            circular = false
        }
        
        local fragments, err = clone.cut_with_enzyme_by_name(sequence, true, "BsaI", false)
        assert.is_nil(err)
        assert.equals(1, #fragments)
        assert.equals("ATGCATCGATCGACTAGCATG", fragments[1].sequence)
    end)

    it("demonstrates GoldenGate assembly", function()
        -- Using real working fragments from Go tests
        local fragment1 = {
            sequence = transform.reverse_complement("GAAGTGCCATTCCGCCTGACCTGAAGACCAGGAGAAACACGTGGCAAACATTCCGGTCTCAAATGGAAAAGAGCAACGAAACCAACGGCTACCTTGACAGCGCTCAAGCCGGCCCTGCAGCTGGCCCGGGCGCTCCGGGTACCGCCGCGGGTCGTGCACGTCGTTGCGCGGGCTTCCTGCGGCGCCAAGCGCTGGTGCTGCTCACGGTGTCTGGTGTTCTGGCAGGCGCCGGTTTGGGCGCGGCACTGCGTGGGCTCAGCCTGAGCCGCACCCAGGTCACCTACCTGGCCTTCCCCGGCGAGATGCTGCTCCGCATGCTGCGCATGATCATCCTGCCGCTGGTGGTCTGCAGCCTGGTGTCGGGCGCCGCCTCCCTCGATGCCAGCTGCCTCGGGCGTCTGGGCGGTATCGCTGTCGCCTACTTTGGCCTCACCACACTGAGTGCCTCGGCGCTCGCCGTGGCCTTGGCGTTCATCATCAAGCCAGGATCCGGTGCGCAGACCCTTCAGTCCAGCGACCTGGGGCTGGAGGACTCGGGGCCTCCTCCTGTCCCCAAAGAAACGGTGGACTCTTTCCTCGACCTGGCCAGAAACCTGTTTCCCTCCAATCTTGTGGTTGCAGCTTTCCGTACGTATGCAACCGATTATAAAGTCGTGACCCAGAACAGCAGCTCTGGAAATGTAACCCATGAAAAGATCCCCATAGGCACTGAGATAGAAGGGATGAACATTTTAGGATTGGTCCTGTTTGCTCTGGTGTTAGGAGTGGCCTTAAAGAAACTAGGCTCCGAAGGAGAGGACCTCATCCGTTTCTTCAATTCCCTCAACGAGGCGACGATGGTGCTGGTGTCCTGGATTATGTGGTACGCGTCTTCAGGCTAGGTGGAGGCTCAGTG"),
            circular = false
        }
        local fragment2 = {
            sequence = "GAAGTGCCATTCCGCCTGACCTGAAGACCAGTACGTACCTGTGGGCATCATGTTCCTTGTTGGAAGCAAGATCGTGGAAATGAAAGACATCATCGTGCTGGTGACCAGCCTGGGGAAATACATCTTCGCATCTATATTGGGCCACGTCATTCATGGTGGTATCGTCCTGCCGCTGATTTATTTTGTTTTCACACGAAAAAACCCATTCAGATTCCTCCTGGGCCTCCTCGCCCCATTTGCGACAGCATTTGCTACGTGCTCCAGCTCAGCGACCCTTCCCTCTATGATGAAGTGCATTGAAGAGAACAATGGTGTGGACAAGAGGATCTCCAGGTTTATTCTCCCCATCGGGGCCACCGTGAACATGGACGGAGCAGCCATCTTCCAGTGTGTGGCCGCGGTGTTCATTGCGCAACTCAACAACGTAGAGCTCAACGCAGGACAGATTTTCACCATTCTAGTGACTGCCACAGCGTCCAGTGTTGGAGCAGCAGGCGTGCCAGCTGGAGGGGTCCTCACCATTGCCATTATCCTGGAGGCCATTGGGCTGCCTACTCATGATCTGCCTCTGATCCTGGCTGTGGACTGGATTGTGGACCGGACCACCACGGTGGTGAATGTGGAAGGGGATGCCCTGGGTGCAGGCATTCTCCACCACCTGAATCAGAAGGCAACAAAGAAAGGCGAGCAGGAACTTGCTGAGGTGAAAGTGGAAGCCATCCCCAACTGCAAGTCTGAGGAGGAAACCTCGCCCCTGGTGACACACCAGAACCCCGCTGGCCCCGTGGCCAGTGCCCCAGAACTGGAATCCAAGGAGTCGGTTCTGTGAAGAGCTTAGAGACCGACGACTGCCTAAGGACATTCGCTGCGTCTTCAGGCTAGGTGGAGGCTCAGTG",
            circular = false
        }
        local vector = {
            sequence = "TAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGGCCTACTATTAGCAACAACGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGAACCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACCTGCACCAGTCAGTAAAACGACGGCCAGTAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTTGGTTCAGGTGGAGTGGGAGTAgtcttcGCcatcgCtACTAAAagccagataacagtatgcgtatttgcgcgctgatttttgcggtataagaatatatactgatatgtatacccgaagtatgtcaaaaagaggtatgctatgaagcagcgtattacagtgacagttgacagcgacagctatcagttgctcaaggcatatatgatgtcaatatctccggtctggtaagcacaaccatgcagaatgaagcccgtcgtctgcgtgccgaacgctggaaagcggaaaatcaggaagggatggctgaggtcgcccggtttattgaaatgaacggctcttttgctgacgagaacagggGCTGGTGAAATGCAGTTTAAGGTTTACACCTATAAAAGAGAGAGCCGTTATCGTCTGTTTGTGGATGTACAGAGTGATATTATTGACACGCCCGGGCGACGGATGGTGATCCCCCTGGCCAGTGCACGTCTGCTGTCAGATAAAGTCTCCCGTGAACTTTACCCGGTGGTGCATATCGGGGATGAAAGCTGGCGCATGATGACCACCGATATGGCCAGTGTGCCGGTCTCCGTTATCGGGGAAGAAGTGGCTGATCTCAGCCACCGCGAAAATGACATCAAAAACGCCATTAACCTGATGTTCTGGGGAATATAAATGTCAGGCTCCCTTATACACAGgcgatgttgaagaccaCGCTGAGGTGTCAATCGTCGGAGCCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCATGGTCATAGCTGTTTCCTGAGAGCTTGGCAGGTGATGACACACATTAACAAATTTCGTGAGGAGTCTCCAGAAGAATGCCATTAATTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGG",
            circular = true
        }
        
        local assembled_sequence, pattern, err = clone.golden_gate(
            {fragment1, fragment2, vector}, 
            clone.default_enzymes.BbsI,
            false
        )

		local expected_sequence = "GTACCACATAATCCAGGACACCAGCACCATCGTCGCCTCGTTGAGGGAATTGAAGAAACGGATGAGGTCCTCTCCTTCGGAGCCTAGTTTCTTTAAGGCCACTCCTAACACCAGAGCAAACAGGACCAATCCTAAAATGTTCATCCCTTCTATCTCAGTGCCTATGGGGATCTTTTCATGGGTTACATTTCCAGAGCTGCTGTTCTGGGTCACGACTTTATAATCGGTTGCATACGTACGGAAAGCTGCAACCACAAGATTGGAGGGAAACAGGTTTCTGGCCAGGTCGAGGAAAGAGTCCACCGTTTCTTTGGGGACAGGAGGAGGCCCCGAGTCCTCCAGCCCCAGGTCGCTGGACTGAAGGGTCTGCGCACCGGATCCTGGCTTGATGATGAACGCCAAGGCCACGGCGAGCGCCGAGGCACTCAGTGTGGTGAGGCCAAAGTAGGCGACAGCGATACCGCCCAGACGCCCGAGGCAGCTGGCATCGAGGGAGGCGGCGCCCGACACCAGGCTGCAGACCACCAGCGGCAGGATGATCATGCGCAGCATGCGGAGCAGCATCTCGCCGGGGAAGGCCAGGTAGGTGACCTGGGTGCGGCTCAGGCTGAGCCCACGCAGTGCCGCGCCCAAACCGGCGCCTGCCAGAACACCAGACACCGTGAGCAGCACCAGCGCTTGGCGCCGCAGGAAGCCCGCGCAACGACGTGCACGACCCGCGGCGGTACCCGGAGCGCCCGGGCCAGCTGCAGGGCCGGCTTGAGCGCTGTCAAGGTAGCCGTTGGTTTCGTTGCTCTTTTCCATTTGAGACCGGAATGTTTGCCACGTGTTTCTCCCACTCCACCTGAACCAAGTCAAAAGCCTCCGGTCGGAGGCTTTTGACTACTGGCCGTCGTTTTACTGACTGGTGCAGGTGCGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATTGAAAAAGGAAGAGTATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTGAAAGTAAAAGATGCTGAAGATCAGTTGGGTGCACGAGTGGGTTACATCGAACTGGATCTCAACAGCGGTAAGATCCTTGAGAGTTTTCGCCCCGAAGAACGTTTTCCAATGATGAGCACTTTTAAAGTTCTGCTATGTGGCGCGGTATTATCCCGTATTGACGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGTTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATAATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAAAGGATCGTTGTTGCTAATAGTAGGCCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAATTAATGGCATTCTTCTGGAGACTCCTCACGAAATTTGTTAATGTGTGTCATCACCTGCCAAGCTCTCAGGAAACAGCTATGACCATGCAAAAAACCCCTCAAGACCCGTTTAGAGGCCCCAAGGGGTTATGCTAGTTATTGCTCAGCGGCTCCGACGATTGACACCTCAGCGAATGTCCTTAGGCAGTCGTCGGTCTCTAAGCTCTTCACAGAACCGACTCCTTGGATTCCAGTTCTGGGGCACTGGCCACGGGGCCAGCGGGGTTCTGGTGTGTCACCAGGGGCGAGGTTTCCTCCTCAGACTTGCAGTTGGGGATGGCTTCCACTTTCACCTCAGCAAGTTCCTGCTCGCCTTTCTTTGTTGCCTTCTGATTCAGGTGGTGGAGAATGCCTGCACCCAGGGCATCCCCTTCCACATTCACCACCGTGGTGGTCCGGTCCACAATCCAGTCCACAGCCAGGATCAGAGGCAGATCATGAGTAGGCAGCCCAATGGCCTCCAGGATAATGGCAATGGTGAGGACCCCTCCAGCTGGCACGCCTGCTGCTCCAACACTGGACGCTGTGGCAGTCACTAGAATGGTGAAAATCTGTCCTGCGTTGAGCTCTACGTTGTTGAGTTGCGCAATGAACACCGCGGCCACACACTGGAAGATGGCTGCTCCGTCCATGTTCACGGTGGCCCCGATGGGGAGAATAAACCTGGAGATCCTCTTGTCCACACCATTGTTCTCTTCAATGCACTTCATCATAGAGGGAAGGGTCGCTGAGCTGGAGCACGTAGCAAATGCTGTCGCAAATGGGGCGAGGAGGCCCAGGAGGAATCTGAATGGGTTTTTTCGTGTGAAAACAAAATAAATCAGCGGCAGGACGATACCACCATGAATGACGTGGCCCAATATAGATGCGAAGATGTATTTCCCCAGGCTGGTCACCAGCACGATGATGTCTTTCATTTCCACGATCTTGCTTCCAACAAGGAACATGATGCCCACAGGTAC"
        
        assert.is_nil(err)
        assert.equals(expected_sequence, assembled_sequence)
    end)

    it("demonstrates ligating linear fragments", function()
        -- Using example from Go tests
        local fragment1 = {
            sequence = "AAAAAA",
            forward_overhang = "GTTG",
            reverse_overhang = "CTAT"
        }
        local fragment2 = {
            sequence = "AAAAAA",
            forward_overhang = "CAAC",
            reverse_overhang = "ATAG"
        }
        
        local sequence, pattern, err = clone.ligate({fragment1, fragment2}, true)
        assert.is_nil(err)
        assert.equals("GTTGAAAAAACTATTTTTTT", sequence)
    end)

	it("demonstrates extracting window flanks from a fragment", function()
	    -- Create a fragment (e.g., from cutting a vector)
	    local vector_fragment = {
	        sequence = "GCGCGCGCATATATATATAT",
	        forward_overhang = "AAAA",
	        reverse_overhang = "TTTT"
	    }
	    
	    -- Extract 8bp flanks from each end to use as search sequences
		-- The left and right are from the perspective of the insert,
		-- not the vector. Hence, the reverse of the vector would be TTTT
		-- but from the insert perspective's it is the forward.
	    local left_flank, right_flank = clone.get_window_from_fragment(vector_fragment, 8, 8)
	    
	    assert.equals("ATATATAT", left_flank)
		assert.equals("GCGCGCGC", right_flank)
	    
	    -- Now these flanks can be used with transform.get_window to find
	    -- what sequence was inserted into the vector. Here, we insert GGTCTC
		-- The true at the end is setting it to a circular sequence
	    local assembled_sequence = "AAAAGCGCGCGCGCATGGCCTTAACGTATATATATTTTTGGTCTC"
	    local insert = transform.get_window(assembled_sequence, left_flank, right_flank, true)
	    
	    assert.equals("TTTTGGTCTCAAAA", insert)
	end)
end)
