-- clone_test.lua
local dnadesign = require("dnadesign")
local clone = dnadesign.clone
local transform = dnadesign.transform
local seqhash = dnadesign.seqhash

-- Define pOpen plasmid (keeping original comment)
-- pOpen plasmid series (https://stanford.freegenes.org/collections/open-genes/products/open-plasmids#description). I use it for essentially all my cloning. -Keoni
local popen = {
   sequence = "TAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGGCCTACTATTAGCAACAACGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGAACCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACCTGCACCAGTCAGTAAAACGACGGCCAGTAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTTGGTTCAGGTGGAGTGGGAGTAGTCTTCGCCATCGCTACTAAAAGCCAGATAACAGTATGCGTATTTGCGCGCTGATTTTTGCGGTATAAGAATATATACTGATATGTATACCCGAAGTATGTCAAAAAGAGGTATGCTATGAAGCAGCGTATTACAGTGACAGTTGACAGCGACAGCTATCAGTTGCTCAAGGCATATATGATGTCAATATCTCCGGTCTGGTAAGCACAACCATGCAGAATGAAGCCCGTCGTCTGCGTGCCGAACGCTGGAAAGCGGAAAATCAGGAAGGGATGGCTGAGGTCGCCCGGTTTATTGAAATGAACGGCTCTTTTGCTGACGAGAACAGGGGCTGGTGAAATGCAGTTTAAGGTTTACACCTATAAAAGAGAGAGCCGTTATCGTCTGTTTGTGGATGTACAGAGTGATATTATTGACACGCCCGGGCGACGGATGGTGATCCCCCTGGCCAGTGCACGTCTGCTGTCAGATAAAGTCTCCCGTGAACTTTACCCGGTGGTGCATATCGGGGATGAAAGCTGGCGCATGATGACCACCGATATGGCCAGTGTGCCGGTCTCCGTTATCGGGGAAGAAGTGGCTGATCTCAGCCACCGCGAAAATGACATCAAAAACGCCATTAACCTGATGTTCTGGGGAATATAAATGTCAGGCTCCCTTATACACAGGCGATGTTGAAGACCACGCTGAGGTGTCAATCGTCGGAGCCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCATGGTCATAGCTGTTTCCTGAGAGCTTGGCAGGTGATGACACACATTAACAAATTTCGTGAGGAGTCTCCAGAAGAATGCCATTAATTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGG",
   circular = true
}

describe("clone package", function()
   describe("cut_with_enzyme_by_name", function()
      it("should fail with fake enzyme", function()
         local fragments, err = clone.cut_with_enzyme_by_name({sequence = popen.sequence, circular = true}, true, "EcoFake", false)
         assert.equals(0, #fragments)
         assert.equals("enzyme not found", err)
      end)
   end)

   describe("cut_with_enzyme", function()
      it("should handle linear sequence with bsaI sites at ends", function()
         local bsai = "GGTCTCAATGC"
         local bsai_complement = "ATGCAGAGACC"
         local sequence = {
            sequence = "ATATATA" .. bsai_complement .. bsai .. "ATGCATCGATCGACTAGCATG" .. bsai_complement .. bsai:sub(1,8),
            circular = false
         }
         
         local fragments, err = clone.cut_with_enzyme_by_name(sequence, true, "BsaI", false)
         assert.is_nil(err)
         assert.equals(1, #fragments)
         assert.equals("ATGCATCGATCGACTAGCATG", fragments[1].sequence)
      end)

      it("should handle circular sequence with same pattern", function()
         local bsai = "GGTCTCAATGC"
         local bsai_complement = "ATGCAGAGACC"
         local sequence = {
            sequence = "ATATATA" .. bsai_complement .. bsai .. "ATGCATCGATCGACTAGCATG" .. bsai_complement .. bsai:sub(1,8),
            circular = true
         }
         
         local fragments, err = clone.cut_with_enzyme_by_name(sequence, true, "BsaI", false)
         assert.is_nil(err)
         assert.equals(2, #fragments)
         assert.equals("ATGCATCGATCGACTAGCATG", fragments[1].sequence)
         assert.equals("TATA", fragments[2].sequence)
      end)

      it("should handle single cut in linear sequence", function()
         local bsai = "GGTCTCAATGC"
         local sequence = {
            sequence = "ATATATATATATATAT" .. bsai .. "GCGCGCGCGCGCGCGCGCGC",
            circular = false
         }
         
         local fragments, err = clone.cut_with_enzyme_by_name(sequence, false, "BsaI", false)
         assert.is_nil(err)
         assert.equals(2, #fragments)
         assert.equals("GCGCGCGCGCGCGCGCGCGC", fragments[1].sequence)
         assert.equals("ATATATATATATATATGGTCTCA", fragments[2].sequence)
      end)

      it("should handle single cut in circular sequence", function()
         local bsai = "GGTCTCAATGC"
         local sequence = {
            sequence = "ATATATATATATATAT" .. bsai .. "GCGCGCGCGCGCGCGCGCGC",
            circular = true
         }
         
         local fragments, err = clone.cut_with_enzyme_by_name(sequence, false, "BsaI", false)
         assert.is_nil(err)
         assert.equals(1, #fragments)
         assert.equals("GCGCGCGCGCGCGCGCGCGCATATATATATATATATGGTCTCA", fragments[1].sequence)
      end)

      it("should handle pOpen without directionality", function()
         local fragments, err = clone.cut_with_enzyme_by_name(popen, false, "BbsI", false)
         assert.is_nil(err)
         assert.equals(2, #fragments)
      end)
   end)

   describe("cut_with_enzyme regression tests", function()
      it("should handle real sequence regression case", function()
         local sequence = "AGCTGCTGTTTAAAGCTATTACTTTGAGACC" -- real sequence causing problems
         
         local part = {sequence = sequence, circular = false}
         local fragments = clone.cut_with_enzyme(part, false, clone.default_enzymes.BsaI, false)
         
         assert.equals(2, #fragments)
         assert.equals("", fragments[1].forward_overhang)
         assert.equals("ACTT", fragments[1].reverse_overhang)
         assert.equals("ACTT", fragments[2].forward_overhang)
         assert.equals("", fragments[2].reverse_overhang)
         
         -- Test assembly
         local assembly = fragments[1].sequence .. fragments[1].reverse_overhang .. fragments[2].sequence
         assert.equals(sequence, assembly)
      end)
   end)

   describe("ligate", function()
      it("should handle circular ligation", function()
         local fragment1 = {sequence = "AAAAAA", forward_overhang = "GTTG", reverse_overhang = "CTAT"}
         local fragment2 = {sequence = "AAAAAA", forward_overhang = "CAAC", reverse_overhang = "ATAG"}
         
         local output, pattern, err = clone.ligate({fragment1, fragment2}, true)
         assert.is_nil(err)
         assert.equals("GTTGAAAAAACTATTTTTTT", output)
      end)

      it("should handle linear ligation", function()
         local fragment1 = {sequence = "AAAAAA", forward_overhang = "GTTG", reverse_overhang = "CTAT"}
         local fragment2 = {sequence = "AAAAAA", forward_overhang = "ATGC", reverse_overhang = "ATAG"}
         
         local output, pattern, err = clone.ligate({fragment1, fragment2}, false)
         assert.is_nil(err)
         assert.equals("GTTGAAAAAACTATTTTTTTGCAT", output)
      end)
   end)

   describe("kmer analysis", function()
      it("should find kmer overlaps and validate them", function()
         local parts = {
            {
               sequence = transform.reverse_complement("CACTCGATAGGTACAACCGGGGTCTCTGTCTCAGCACCGGCAGCAGCAGCACGCGCAGGTGGTCCGGACATCTCGGAGGCAGGTGCACTGGGTACGCGCGCACTGGCACGCGCATGGCTGGCATACGGTATCACGGCAGAGGACGTGAAGCGCATCCTGGACACGCTGGGTCTGGGTTCGGGTGAGTTCGGTTTCCGCCAGCAGGTGCTGGAGGACACGATCCAGCCGGCAATCGCATCGGGTGCAGGTCTGCACTTCGTGGACCTGAGACCGCCATCCTCTTATCTCGTGGCATTGAGT"),
               circular = false
            },
            {
               sequence = "CACTCGATAGGTACAACCGGGGTCTCTGACCCGGAGGCAGCAGCAGGTTACCTGGCAGAGCTGGTGAAGCGCTCGTACTCGAAGGCAGTGCCGGCAGCAGTGAAGGCAGAGGACTGGCTGAAGAAGATCGCACTGCTGGTGGCATCGGAGTCGACGTCGTCGTCGGGTCTGAAGATCCTGAAGTCGCCGCAGCCGGTGAAGTGGGTGTCGCCGGACGGTTTCCCGGTGATCCTGGACCCGAAGAAGCCGATCCAGATGAGACCGCCATCCTCTTATCTCGTGGCCCCGAGCATCAGCGGA",
               circular = false
            },
            {
               sequence = "CACTCGATAGGTACAACCGGGGTCTCTCAGACGCGCCTGCAGCTGATGTTCCTGGGTCAGTTCACGCTGCAGCCGACGATCAACACGAACAAGGACTCGGAGATCGACAAGGAGAAGCTGGCATCGGGTATCGCACCGAACTTCGTGGCATCGCAGATCGCATCGCTGGTGCGCCGCACGGTGGTGCTGGCACACGAGAAGTACGGTATCAAGTCGTTCTGGATCGACAAGGACGAGTACGGTACGATCCCGGCACAGATGGACAATGAGACCGCCATCCTCTTATCTCGTGGTCTCAGC",
               circular = false
            },
            {
               sequence = "CACTCGATAGGTACAACCGGGGTCTCTACAAGCTGAAGGCAGCAATCAAGGAGTCGCTGGTGGAGACGTACACGAACAACGACCTGCTGGAGAACCTGCGCGACCTGGTGGAGAAGGAGGGTTGCCCGGGTGACTGCTCGTCGGTGCCGGAGCTGCCGCCGAAGGGTGACCTGGACCTGAACGAGATCCTGAAGTCGGAGTACGGTGGTTTCTAAATCCCGAGTGAGACCGCCATCCTCTTATCTCGTGGGGGTTAATCTAGTCAGCGCCACGACTACTTCCGCTTCCCCACATAAGCAG",
               circular = false
            }
         }

         local popen_v3_methylated = {
            sequence = "AGGGTAATGGTCTCTCGAGACcAAGTCGTCATAGCTGTTTCCTGAGAGCTTGGCAGGTGATGACACACATTAACAAATTTCGTGAGGAGTCTCCAGAAGAATGCCATTAATTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGGCCTACTATTAGCAACAACGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGAACCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACCTGCACCAGTCAGTAAAACGACGGCCAGTGACTTgGTCTCGAGACCTAGGGATA",
            circular = false
         }

         table.insert(parts, popen_v3_methylated)
         
         local fragments = {}
         for _, part in ipairs(parts) do
            local new_fragments = clone.cut_with_enzyme(part, true, clone.default_enzymes.BsaI, true)
            for _, fragment in ipairs(new_fragments) do
               table.insert(fragments, fragment)
            end
         end

         -- First, ligate the fragments
         local ligation, ligation_pattern, err = clone.ligate(fragments, true)
         assert.is_nil(err)

         -- Now, find kmer overlaps
         local kmer_overlaps, err = clone.find_kmer_overlaps(fragments, ligation, ligation_pattern, 16)
         assert.is_nil(err)
         
         local expected_overlaps = {
            "GACTTGGTCTCAGCAC",
            "AAATCCCGAGACCAAG",
            "AGATGGACAAGCTGAA",
            "CCGATCCAGACGCGCC",
            "CCTCCGGGTCCACGAA"
         }

         for i, overlap in ipairs(kmer_overlaps) do
            assert.equals(expected_overlaps[i], overlap.kmer)
         end

         -- Test finding kmers in example sequences
         local test_reads = {
            {
               sequence = "CTGCCAGTATTTACTCGTTCAGTTAGTATTGCTAAGGTTAACACAAAGACACCGACAACTTCTTCAGCACCTAGGGTAATGGTCTCTCGAGACAGAAGATCGTCATAGCTGTTTCCTGGCCGTGAAGAAGAGTTTCGGGATGGCGTAGCAGCAGCGATTCGTTATGCCCGTGCGCTGGGTAATAAAAAATTAACTGTCTGGTCGGTAAAACGACGGCCAGTGACTGGTCTCAGCACCGGCAGCAGCAGCACGCGCAGGTGGTCCGGACATCTCGGAGGCAGGTGCACTGGGTACGCGCGCACTGGCACGCGCATGGCTGGCATACGGTATCACGGCAGAGGACGTGAAGCGCATCCTGGACACGCTGGGTCTGGGTTCGGGTGAGTTCGGTTTCCGCCAGCAGGTGCTGGAGGACACGATCCAGCCGGCAATCGCATCGGGTGCAGGTCTGCACTTCGTGGACCCGGAGGCAGCAGCAGGTTACCTGGCAGAGCTGGTGAAGCGCTCGTACTCGAAGGCAGTGCAGCAGTGAAGGCAGAGGACTGGCTGAAGAAGATCGCACTGCTGGTGGCATCGGAGTCGACGTCGTCGTCGGGTCTGAAGATATTCCTGAAGTCGCCGCAGCCGGTGAAGTGGGTGTCGCCGGACGGTTTCCCGGTGATCCTGGACCCGAAGAAGCCGATCCAGATGAGACCGCCATCCTC",
            },
            {
               sequence = "ATGTTATGTAGTCTTACCTGACTCACTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTCTTCGGCACCTTTAGGGAACCAGGCTTAACGGTCGTAACTCCCTCACCTACGGACTCGACAATACCTGCGGCTTCGTGCCCGGTCTGACCGGCAGCGGCATGCAGGTGCGATGAGTCGCCCCTAAGCAGCCACGGATCAAGGATGGCGGTCTCATCTGGATCGGCTTCTTCGGGTCCAGGATCACCGGGAAACCGTCCGGCGACACCCACTTCACCGGCTGCGGCGACTTCAGGATCTTCAGACCCGACGACGACATCAACTCCGATGCCACCAGCAGTGCGATCTTCTTCAGCCAGTCCTCTGCCTTCACTGCTGCCGGCACTGCCTTCGAGTACCAGCGCTTCGCCCGGCTCTGCCAGGTAACCTGCTGCTGCCTGCGGGTCCACGAAGTGCAGACCTGCACCCGATGCGATTCCCGGCTGGATCGTGTCCTCCAGCACCTGCTGGCGGAAACCGAACTCACCCGAACCCAGACGCGGCATGTCGGGATCGCTACCGCGTGTTCTGCCGTGATACCGTATGCCAGCCATGCGCGTGCCAGTGCGCGCGTCCCCGTGCACCTGCCTCCGAGATGTGCCGGACCACCTGCGCGTGCTGCTGCTGCCGGTGCTGAGACCAAGTCACTGGCCGTCGTTTTACCGATTTTGGCGTCTCACAAGGCAAGGCGACGAAAGAGAAAGTGATCGAACAGGAACGGGTCAGCGCCGCGCCGTTTTGCGAAAAGCTGAACATCCCCGGAAACAGCTATGACGACTTGGTCTCGAGAGACCATTACCCTAGGTCCTGAAGAAAGTTCTGGTGTCTTTGTGTC",
            },
            {
               sequence = "ATGTTTTTGTACGTACTCGTTCAGTTACGTATTGCTAAGGTTAACACAAAGACACCGACAACTTTCTTCAGCACCTAAAGCACTCTTAGGCCTCTGCGTACTCCGGTGCCAGGATGATGGTCTCCGAGTCCTGGTCCACCACACCTGCGTTCTGGATGGCTTCTTCGGGTCCAGGTTCACCGGGAAACCGTCCGGCGACACCCACTTCACCGGCTGCGGCCGGTTTAGGATCTTCGAGCCCGACGACGACATCAACTCCGATGCCACCAGCAGTGCGATCTTCTTCAGCCAGTCCTCTGCCTTCACTGCTGCCGGCACTGCCTTCAAGTACGAGCGCTCACCAGCTCTGCCAGGTAACCTGCTGCTGCCTCCGGGTCCACGAAGTGCAGACCTGCACCCGATGCGATTGCCGGCTGGATCGTGTCCTCCAGCACCTGCTGGCGGAAACCGAACTCACCGAACCCAGACCCAGCGTGTCCAGGATGCGCTTCGCGTCCTCTGCCGTGATCCGTATGCCAGCCATGCGCGTGCCAGTGCGCGCGTACCCAGTGCACCTGCCTCCGAGATGTCCGGACCACCTGCGCGTGCTGCTGCTGCCGGTGCTAAAGCAAGTCACTGGCCGTCGTTTTACTGACTCAGGGTCGGAACAGGAGAGCGCACGAGGAGGAAGCTCCAGGGGGAAACGCCTCGTACTTTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCGGGGGACGAGCGCCTATGGAAATTAATGGCATTCTTCTGAAACCTTCACGAAATTTGTTAATGTGTGTCATCACCTAAGCTCTCGGGGAACAGGTTGTG",
            }
         }

         local expected_overlap_results = {
            "CCTCCGGGTCCACGAA",
            "GACTTGGTCTCAGCAC",
            "CCTCCGGGTCCACGAA"
         }

         for i, read in ipairs(test_reads) do
            local overlaps = clone.find_kmers(kmer_overlaps, read.sequence)
            assert.equals(expected_overlap_results[i], overlaps[1].kmer)
         end
      end)

      it("should fail with too few fragments", function()
         local overlaps, err = clone.find_kmer_overlaps({}, "", {}, 0)
         assert.equals("need at least two fragments to find overlaps", err)
      end)

      it("should fail with too small kmer", function()
         local overlaps, err = clone.find_kmer_overlaps({{}, {}}, "", {}, 0)
         assert.equals("need at least a kmer of 12", err)
      end)
   end)

   describe("get_window_from_fragment", function()
	   it("should extract left and right flanks from a simple fragment", function()
	      local fragment = {
	         sequence = "ATCGATCGATCG",
	         forward_overhang = "AAAA",
	         reverse_overhang = "TTTT"
	      }
	      
		  -- left and right as assuming the fragment is the vector
		  -- and we are considering from the perspective of an insert
	      local left_flank, right_flank = clone.get_window_from_fragment(fragment, 4, 4)
	      
	      assert.equals("ATCG", left_flank)
		  assert.equals("ATCG", right_flank)
	   end)
	   
	   it("should handle different flank lengths", function()
	      local fragment = {
	         sequence = "GCGCGCGCGCGCGC",
	         forward_overhang = "ATAT",
	         reverse_overhang = "CGCG"
	      }
	      
	      local left_flank, right_flank = clone.get_window_from_fragment(fragment, 6, 10)
	      
	      assert.equals("GCGCGCGCGC", left_flank)
		  assert.equals("GCGCGC", right_flank)
	   end)
	   
	   it("should handle minimal flank lengths", function()
	      local fragment = {
	         sequence = "AAAA",
	         forward_overhang = "GG",
	         reverse_overhang = "CC"
	      }
	      
	      local left_flank, right_flank = clone.get_window_from_fragment(fragment, 4, 4)
	      
	      assert.equals("AAAA", left_flank)
		  assert.equals("AAAA", right_flank)
	   end)
	end)
end)
