name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cffi
        pip install pdoc3  # Install pdoc3
        pip install -e ./py  # Install your package in editable mode

    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs ./py/dnadesign

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # Only deploy on the main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dnadesign
