name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.11.0

    - name: Build Go shared library
      working-directory: ./py
      run:
        CC="zig cc -target x86_64-linux-gnu" CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o dnadesign/libdnadesign.so -buildmode=c-shared lib.go

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you're using

    - name: Build wheel
      working-directory: ./py
      run: |
        pip install wheel packaging setuptools cffi
        python setup.py bdist_wheel --plat-name manylinux2014_x86_64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3  # Install pdoc3
        pip install -e ./py  # Install your package in editable mode

    - name: Generate documentation
      run: |
        python -m venv test_env
        source test_env/bin/activate
        pip install ./py/dist/*.whl
        python -c "from dnadesign import parser; print('Library loaded successfully')"
        pip install pdoc
        pdoc --html --output-dir docs ./py/dnadesign

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # Only deploy on the main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dnadesign
