on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x,]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./lib/...
  openbsd-test:
    runs-on: ubuntu-latest
    name: Tests on OpenBSD
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup OpenBSD VM
      uses: vmactions/openbsd-vm@v1
      with:
        prepare: |
          pkg_add curl
          curl -L https://dl.google.com/go/go1.21.5.openbsd-amd64.tar.gz -o go1.21.5.openbsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.21.5.openbsd-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version
          go install golang.org/x/tools/cmd/goimports@latest
    - name: Run tests in OpenBSD
      run: export PATH=$PATH:/usr/local/go/bin && go test -v ./lib/...

