on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x,]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v ./lib/...
  test-external:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download minimap2
      run: |
        curl -L https://github.com/lh3/minimap2/releases/download/v2.26/minimap2-2.26_x64-linux.tar.bz2 | tar -jxvf -
        mkdir -p $HOME/bin
        cp ./minimap2-2.26_x64-linux/minimap2 $HOME/bin
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Test external
      run: go test -v ./external/...
  openbsd-test:
    runs-on: ubuntu-latest
    name: 1.21.5 openbsd
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run OpenBSD tests
      uses: vmactions/openbsd-vm@v1
      with:
        prepare: |
          pkg_add curl
          curl -L https://dl.google.com/go/go1.21.5.openbsd-amd64.tar.gz -o go1.21.5.openbsd-amd64.tar.gz
          tar -C /usr/local -xzf go1.21.5.openbsd-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go install golang.org/x/tools/cmd/goimports@latest
        run: |
          export PATH=$PATH:/usr/local/go/bin
          go test -v ./lib/...
